//! Ordnung GUI — desktop wrapper around `ordnung-core`.
//!
//! Mirrors the CLI's role per `ordnung-architecture`: all policy/UI lives here,
//! engines stay in core. Browses the catalog; double-click a track to convert it.
//! Conversion (and any other I/O) runs in a background thread; the engine itself
//! is the existing `ordnung-core::convert` Phase-4 implementation.

#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod app;
mod audio;
mod config;
mod covers;
mod dig;
mod inspector;
mod jobs;
mod macos_drag;
mod macos_menu;
mod macos_pasteboard;
mod modals;
mod onboarding;
mod player;
mod records;
mod search_box;
mod sidebar;
mod table;
mod tex;
mod ui;
mod util;
mod versions;
mod views;
mod vinyl_sheet;
mod webview;

use audio::{fmt_time, AudioEngine, PlayState};
use config::{Config, NavPrimary, StartupView};
use covers::*;
use dig::DigPath;
use eframe::egui;
use egui_extras::{Column, TableBuilder};
use onboarding::Tour;
use ordnung_core::analysis::{self, AnalysisParams, ANALYZER_VERSION, WAVEFORM_FULLTRACK_VERSION};
use ordnung_core::convert::{self, ConvertSpec};
use ordnung_core::discogs;
use ordnung_core::model::key::Camelot;
use ordnung_core::model::{
    Analysis, Format, Id, Playlist, Tags, Track, TranscodeVerdict, VinylList, VinylRecord,
};
use ordnung_core::search::{ScoredHit, SearchHit};
use ordnung_core::{
    best_copy_index, scan, tag, Catalog, DuplicateGroup, DuplicateKind, ScannedTrack,
};
use player::*;
use rayon::prelude::*;
use records::{RecordFetched, RecordSearch, SearchScope, RECORD_DEBOUNCE, SCOPE_TOGGLE_W};
use sidebar::*;
use std::collections::{HashMap, HashSet, VecDeque};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};
use std::sync::mpsc::{self, Receiver, Sender};
use std::sync::Arc;
use std::thread;
use std::time::Duration;
use table::*;
use tex::{Tex, TexGraveyard};
use ui::hover::HoverNoteExt;
use util::*;
use vinyl_sheet::{SheetFetched, VinylSheet};

/// Compile-time switch for the native rekordbox USB export. The format is
/// still being reverse engineered, so release DMGs build without the
/// `usb-export` feature and hide the whole device surface; local dev builds
/// (`make run` / `make app`) turn it on. Users get music to the players the
/// classic way meanwhile: drop tagged files into rekordbox (see the tour's
/// rekordbox step).
pub(crate) const USB_EXPORT: bool = cfg!(feature = "usb-export");

/// [`ordnung_core::usb::detect_volumes`], but always empty when the USB
/// export is compiled out. Every device entry point keys off the mounted
/// volume list, so "no volumes, ever" erases the Devices section, the device
/// view, and the export menus in one place.
pub(crate) fn detect_usb_volumes() -> Vec<ordnung_core::usb::UsbVolume> {
    if USB_EXPORT {
        ordnung_core::usb::detect_volumes()
    } else {
        Vec::new()
    }
}

fn main() -> eframe::Result<()> {
    // Pull a repo-root `.env` into the process environment before anything reads
    // it, so a local `DISCOGS_TOKEN=…` line works for `cargo run`/`make run`
    // without exporting it in the shell. Absent file → no-op (Finder launches
    // fall back to the token saved in ~/.ordnung/config.toml); we never override
    // a variable already set in the real environment.
    let _ = dotenvy::dotenv();
    let db_path = default_db_path().unwrap_or_else(|| PathBuf::from("ordnung.db"));
    let mut viewport = egui::ViewportBuilder::default()
        .with_inner_size([1100.0, 680.0])
        .with_min_inner_size([720.0, 420.0])
        .with_title("Ordnung");
    if let Some(icon) = load_app_icon() {
        viewport = viewport.with_icon(icon);
    }
    let opts = eframe::NativeOptions {
        viewport,
        ..Default::default()
    };
    eframe::run_native(
        "Ordnung",
        opts,
        Box::new(move |cc| Ok(Box::new(App::new(db_path, cc.egui_ctx.clone())))),
    )
}

/// Decode the embedded app icon (committed at `assets/icon.png`, generated by
/// `tools/build-app.sh` from `tools/icon.svg`). Returns `None` if the bytes
/// can't be decoded, in which case eframe falls back to its default icon.
fn load_app_icon() -> Option<egui::IconData> {
    let bytes = include_bytes!("../assets/icon.png");
    let img = image::load_from_memory(bytes).ok()?;
    let rgba = img.to_rgba8();
    let (w, h) = rgba.dimensions();
    Some(egui::IconData {
        rgba: rgba.into_raw(),
        width: w,
        height: h,
    })
}

/// One catalog track flattened for display.
struct TrackRow {
    id: Id,
    artist: String,
    title: String,
    album: String,
    genre: String,
    duration: String,
    bpm: String,
    key: String,
    format: Format,
    format_label: String,
    bitrate: String,
    /// Free-text comment from the file's tag (ID3 COMM / Vorbis COMMENT), shown
    /// read-only in the Notes column. Empty string when the track has no comment.
    notes: String,
    /// Pre-formatted relative age for the Added column ("today", "3d ago").
    added: String,
    /// Per-bin peak envelope (`Analysis::waveform_preview`) for the inline
    /// Waveform column; empty when the track isn't analyzed. Loaded alongside the
    /// other analysis-derived fields in `load_rows`, so the cell paints with no
    /// extra query.
    waveform: Vec<u8>,
    /// Per-bin `[low, mid, high]` band energy (`Analysis::waveform_bands`) for the
    /// Waveform column's colour; empty for pre-v10 analyses (cell degrades to a
    /// height ramp).
    waveform_bands: Vec<u8>,
    /// Raw `added_at` unix timestamp (seconds) behind `added`, so the Added
    /// column sorts by true recency rather than the rounded label.
    added_at: i64,
    source_path: PathBuf,
    // Raw values behind the formatted columns, kept so header sorting orders
    // numerically/musically instead of lexically ("100" vs "99", "10A" vs "2A").
    // `None` = unknown ("—" in the cell), and sorts to one end.
    dur_ms: Option<u64>,
    bpm_val: Option<f32>,
    bitrate_val: Option<u32>,
    /// Camelot wheel order: number * 2 + side (B after A within a number).
    key_sort: Option<u16>,
    /// Camelot wheel position behind the `key` label, used to colour the key
    /// chip (harmonic neighbours share a hue). `None` = unanalyzed ("—").
    camelot: Option<Camelot>,
    /// Transcode-quality verdict from spectral analysis. `None` = not analyzed at
    /// v6+ (shows "—"); the Quality column and its sort read from here.
    quality: Option<TranscodeVerdict>,
    /// Detected low-pass cutoff and estimated lossy source, for the cell tooltip.
    quality_cut_hz: Option<f32>,
    quality_src: Option<&'static str>,
    /// Severity rank for sorting (0 clean … 3 likely-lossy); `None` sorts to the end.
    quality_sort: Option<u8>,
    /// Whether this row had embedded cover art at scan time (drives whether we
    /// even try to load a thumbnail from the catalog).
    has_cover: bool,
    /// Whether the catalog has a successfully-fetched external (Discogs)
    /// artwork row for this track. Combined with `has_cover` to decide
    /// whether the cover cell should attempt a load at all.
    has_external_cover: bool,
}

impl TrackRow {
    /// The text the per-column filter matches against for `col` — the same value
    /// the cell shows. Returns `""` for columns without filterable text (Cover),
    /// and the chip label for the Quality column (so e.g. "lossy" matches).
    fn filter_text(&self, col: TableColumn) -> &str {
        match col {
            TableColumn::Cover => "",
            TableColumn::Waveform => "",
            TableColumn::Artist => &self.artist,
            TableColumn::Title => &self.title,
            TableColumn::Album => &self.album,
            TableColumn::Genre => &self.genre,
            TableColumn::Duration => &self.duration,
            TableColumn::Bpm => &self.bpm,
            TableColumn::Key => &self.key,
            TableColumn::Format => &self.format_label,
            TableColumn::Bitrate => &self.bitrate,
            TableColumn::Quality => self.quality.map_or("—", |v| quality_chip(v).0),
            TableColumn::Notes => &self.notes,
            TableColumn::Added => &self.added,
        }
    }
}

/// Cached thumbnail status — `Some(texture)` = ready, `None` = no cover or
/// decode failed (cached so we don't retry every frame). Stored as [`Tex`]
/// so eviction from anywhere in the frame is safe (see `tex.rs`).
type CoverEntry = Option<Tex>;

/// Load state of a table-row thumbnail. A *missing* `cover_cache` entry means
/// "not requested yet"; `Loading` means a background decode is in flight (so we
/// don't request it again every frame); `Ready(Some)` is the decoded texture and
/// `Ready(None)` means the track has no usable cover (cached so we never retry).
/// Decoding the PNG and reading the catalog both happen off the UI thread, so a
/// fast scroll never blocks on disk or image decode — the row shows a placeholder
/// until the worker hands back a texture.
enum ThumbState {
    Loading,
    Ready(CoverEntry),
}

/// Which set of tracks the main table shows: the whole catalog ("Library"), the
/// members of one playlist, or the duplicate-finder report. Selected from the
/// left sidebar.
#[derive(Clone, PartialEq, Eq)]
enum LibraryView {
    Library,
    /// The "recently added" inbox — fresh imports that still need analysis and/or
    /// a Discogs song-data fetch. A track expires out of this view automatically
    /// once it's both analyzed (at the current analyzer version) and fetched, so
    /// it reads as a self-clearing to-do list. Backed by the flat track table.
    RecentlyAdded,
    Playlist(Id),
    /// The duplicate finder — rendered as grouped blocks, not the flat table.
    Duplicates,
    /// Tracks whose source file is gone — rendered as a review list, not the table.
    Missing,
    /// The user's Discogs vinyl collection — rendered as a grid of cover art,
    /// not the flat track table. Backed by the local `vinyl_collection` cache.
    Vinyl,
    /// A mounted removable volume (USB stick / external drive), keyed by its
    /// mount path, showing either the whole device (`None`) or one playlist
    /// from its rekordbox export (`Some(playlist id)`). The tracks live on the
    /// device, not in the catalog — rows are built from `usb_tracks` (with
    /// synthetic ids, see [`usb_track_id`]) and rendered in the normal table.
    Usb(PathBuf, Option<u32>),
}

/// A sortable table column. The cover column isn't sortable, so it has no
/// variant. Paired with a direction (`true` = ascending) in `App::sort`.
#[derive(Clone, Copy, PartialEq, Eq)]
enum SortColumn {
    Artist,
    Title,
    Album,
    Genre,
    Duration,
    Bpm,
    Key,
    Format,
    Bitrate,
    Quality,
    Notes,
    Added,
}

/// One column of the track table. The cover thumbnail plus the data columns
/// are reorderable and show/hideable from the header's right-click menu; the
/// chosen order and hidden set persist to `~/.ordnung/config.toml`. The trailing
/// `remainder` spacer is structural (it just fills slack so the striped rows span
/// the full width) and is intentionally not represented here.
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
enum TableColumn {
    Cover,
    /// Inline colored waveform thumbnail (like Serato/rekordbox). Not sortable;
    /// painted from the row's `waveform`/`waveform_bands`, colored per the
    /// `waveform_color_mode` setting.
    Waveform,
    Artist,
    Title,
    Album,
    Genre,
    Duration,
    /// Detected/tagged tempo in BPM (`tracks.bpm_tag`), shown to two decimals.
    Bpm,
    Key,
    Format,
    Bitrate,
    Quality,
    /// Free-text notes — the file's comment tag (ID3 COMM / Vorbis COMMENT),
    /// surfaced read-only here. See `Tags::comment` in ordnung-core.
    Notes,
    /// When the track was first scanned into the catalog (`tracks.added_at`),
    /// shown as a relative age ("today", "3d ago"). Sort it descending to see
    /// the most recent import at the top.
    Added,
}

impl TableColumn {
    /// Every column in the default left-to-right order. Doubles as the source of
    /// truth for "which columns exist": the reorder menu lists these, and loading
    /// a saved layout appends any column missing from it (so a config written by
    /// an older build still shows columns added since).
    const DEFAULT_ORDER: [TableColumn; 14] = [
        TableColumn::Cover,
        TableColumn::Artist,
        TableColumn::Title,
        TableColumn::Album,
        TableColumn::Genre,
        TableColumn::Duration,
        TableColumn::Waveform,
        TableColumn::Added,
        TableColumn::Bpm,
        TableColumn::Key,
        TableColumn::Format,
        TableColumn::Bitrate,
        TableColumn::Quality,
        TableColumn::Notes,
    ];

    /// Stable key persisted to config — deliberately independent of the enum
    /// order and the display label so reordering the enum or renaming a header
    /// can't corrupt a saved layout.
    fn key(self) -> &'static str {
        match self {
            TableColumn::Cover => "cover",
            TableColumn::Waveform => "waveform",
            TableColumn::Artist => "artist",
            TableColumn::Title => "title",
            TableColumn::Album => "album",
            TableColumn::Genre => "genre",
            TableColumn::Duration => "duration",
            TableColumn::Bpm => "bpm",
            TableColumn::Key => "key",
            TableColumn::Format => "format",
            TableColumn::Bitrate => "bitrate",
            TableColumn::Quality => "quality",
            TableColumn::Notes => "notes",
            TableColumn::Added => "added",
        }
    }

    /// Parse a persisted key back into a column, ignoring anything unknown (a key
    /// from a newer build, or a typo'd hand-edited config).
    fn from_key(s: &str) -> Option<TableColumn> {
        TableColumn::DEFAULT_ORDER
            .into_iter()
            .find(|c| c.key() == s)
    }

    /// Display name: the header text, and the row label in the reorder menu. The
    /// cover header draws no text, but the column still needs a name in the menu.
    fn label(self) -> &'static str {
        match self {
            TableColumn::Cover => "Cover",
            TableColumn::Waveform => "Wave",
            TableColumn::Artist => "Artist",
            TableColumn::Title => "Title",
            TableColumn::Album => "Album",
            TableColumn::Genre => "Genre",
            TableColumn::Duration => "Dur",
            TableColumn::Bpm => "BPM",
            TableColumn::Key => "Key",
            TableColumn::Format => "Format",
            TableColumn::Bitrate => "kbps",
            TableColumn::Quality => "Qual",
            TableColumn::Notes => "Notes",
            TableColumn::Added => "Added",
        }
    }

    /// The sort key cycled by clicking this header, or `None` for the (unsortable)
    /// cover column.
    fn sort_column(self) -> Option<SortColumn> {
        Some(match self {
            TableColumn::Cover => return None,
            TableColumn::Waveform => return None,
            TableColumn::Artist => SortColumn::Artist,
            TableColumn::Title => SortColumn::Title,
            TableColumn::Album => SortColumn::Album,
            TableColumn::Genre => SortColumn::Genre,
            TableColumn::Duration => SortColumn::Duration,
            TableColumn::Bpm => SortColumn::Bpm,
            TableColumn::Key => SortColumn::Key,
            TableColumn::Format => SortColumn::Format,
            TableColumn::Bitrate => SortColumn::Bitrate,
            TableColumn::Quality => SortColumn::Quality,
            TableColumn::Notes => SortColumn::Notes,
            TableColumn::Added => SortColumn::Added,
        })
    }

    /// The narrowest this column may be dragged. Also the floor for the
    /// right-edge cap in `spec`: a column can always reach its minimum even in a
    /// window too narrow to hold it.
    fn min_width(self, cover_px: f32) -> f32 {
        match self {
            TableColumn::Cover => cover_px + 6.0,
            TableColumn::Waveform => 60.0,
            TableColumn::Artist => 80.0,
            TableColumn::Title => 80.0,
            TableColumn::Album => 60.0,
            TableColumn::Genre => 60.0,
            TableColumn::Duration => 40.0,
            TableColumn::Bpm => 56.0,
            TableColumn::Key => 40.0,
            TableColumn::Format => 50.0,
            TableColumn::Bitrate => 50.0,
            TableColumn::Quality => 48.0,
            TableColumn::Notes => 80.0,
            TableColumn::Added => 60.0,
        }
    }

    /// This column's default width, used before the user has resized it (and by
    /// the table to lay out the right-edge drag cap on the first frame, when no
    /// measured width exists yet).
    fn default_width(self, cover_px: f32) -> f32 {
        match self {
            TableColumn::Cover => cover_px + 6.0,
            TableColumn::Waveform => 140.0,
            TableColumn::Artist => 180.0,
            TableColumn::Title => 260.0,
            TableColumn::Album => 180.0,
            TableColumn::Genre => 110.0,
            TableColumn::Duration => 60.0,
            TableColumn::Bpm => 74.0,
            TableColumn::Key => 55.0,
            TableColumn::Format => 60.0,
            TableColumn::Bitrate => 70.0,
            TableColumn::Quality => 66.0,
            TableColumn::Notes => 200.0,
            TableColumn::Added => 90.0,
        }
    }

    /// This column's egui_extras width spec (the same sizes the table used when
    /// columns were hard-coded). `cover_px` is the thumbnail edge length.
    /// `width` overrides the initial width with the user's saved value (see
    /// `App::column_widths`); `None` uses the per-column default. `max` caps how
    /// wide it may be dragged — the caller passes the space left before the
    /// table's right edge, so a resize can never push the column's own edge (and
    /// its drag handle) off screen. The Cover column is a fixed size and ignores
    /// both.
    fn spec(self, cover_px: f32, width: Option<f32>, max: Option<f32>) -> Column {
        if self == TableColumn::Cover {
            return Column::exact(cover_px + 6.0);
        }
        let min = self.min_width(cover_px);
        let col = Column::initial(width.unwrap_or_else(|| self.default_width(cover_px)))
            .at_least(min)
            .clip(self.clips());
        // Never cap below the minimum: a very narrow window must still leave the
        // column draggable within its own legal range.
        match max {
            Some(m) => col.at_most(m.max(min)),
            None => col,
        }
    }

    /// Whether this column clips its content rather than forcing itself wider.
    /// The free-text columns clip; the short numeric ones don't. Waveform stays
    /// unclipped because when it leads the row its paint stretches left across the
    /// blank order gutter (see the flush-left rect in table.rs), which a cell clip
    /// would cut off.
    fn clips(self) -> bool {
        matches!(
            self,
            TableColumn::Artist
                | TableColumn::Title
                | TableColumn::Album
                | TableColumn::Genre
                | TableColumn::Notes
        )
    }
}

/// Open state for the per-column filter search bar (double-click a header). The
/// bar anchors at `pos`; `focus` is true for the one frame after opening so the
/// text field grabs the keyboard without an extra click.
struct ColFilterPopup {
    col: TableColumn,
    pos: egui::Pos2,
    focus: bool,
}

/// egui drag-and-drop payload carried by a plain row-drag: the track ids being
/// dragged (the whole selection, in visible order). Dropping it onto a playlist
/// in the left sidebar adds those tracks. (Option-drag uses the native macOS
/// drag-out to rekordbox instead and never sets this payload.)
#[derive(Clone)]
struct DraggedTracks(Vec<Id>);

/// Drag payload for rows from a mounted device (synthetic ids — see
/// [`usb_track_id`]). A distinct type from [`DraggedTracks`] so catalog drop
/// targets (playlists) can't accept device rows they have no ids for; the one
/// target that accepts these is the sidebar's Library source tab, where a
/// drop means "copy these files into my library".
struct DraggedUsbTracks(Vec<Id>);

/// Edit buffers for the inspector's editable Core tag fields. Held as plain
/// strings so they bind directly to `TextEdit`s; converted back to typed `Tags`
/// on save. Compared against a saved baseline to drive the dirty state.
#[derive(Default, Clone, PartialEq, Eq)]
struct TagEdit {
    title: String,
    artist: String,
    album_artist: String,
    album: String,
    genre: String,
    label: String,
    year: String,
    comment: String,
}

impl TagEdit {
    fn from_tags(t: &Tags) -> Self {
        TagEdit {
            title: t.title.clone().unwrap_or_default(),
            artist: t.artist.clone().unwrap_or_default(),
            album_artist: t.album_artist.clone().unwrap_or_default(),
            album: t.album.clone().unwrap_or_default(),
            genre: t.genre.clone().unwrap_or_default(),
            label: t.label.clone().unwrap_or_default(),
            year: t.year.map(|y| y.to_string()).unwrap_or_default(),
            comment: t.comment.clone().unwrap_or_default(),
        }
    }
}

/// What the user asked the inspector to do this frame. Returned from
/// `draw_inspector` and acted on after its borrow of `self` ends.
enum InspectorAction {
    /// Imprint the fetched external cover into the source file.
    EmbedCover(Id, PathBuf),
    /// Commit the edited Core fields to the catalog only.
    SaveToCatalog(Id),
    /// Commit to the catalog AND write the tags into the source file.
    WriteToFile(Id, PathBuf),
    /// Open the record sheet for the Discogs release this track is matched to,
    /// so its full tracklist (and whether the record is in the collection or the
    /// wantlist) is one click from the track.
    ViewRelease(Id),
}

/// State for the conversion modal. Also lets the user rename the track
/// (catalog-only — never touches the source file unless they convert in-place,
/// and even then only the bytes are rewritten, not the tags).
struct ConvertModal {
    track_id: Id,
    track_label: String,
    source_path: PathBuf,
    source_format: Format,
    // Editable display name. Saved to catalog tags via `update_tags`.
    // Conversion options.
    target: Format,
    bitrate_kbps: String,
    out_dir: Option<PathBuf>,
    in_place: bool,
    error: Option<String>,
}

/// Batch conversion of the current multi-selection to one target format. Unlike
/// `ConvertModal` there's no per-track name editing — just the shared conversion
/// options applied to every selected track. Each output is rehydrated from the
/// catalog (full tags + cover), exactly like a single convert.
struct BatchConvert {
    ids: Vec<Id>,
    target: Format,
    bitrate_kbps: String,
    out_dir: Option<PathBuf>,
    in_place: bool,
    error: Option<String>,
}

/// One Discogs release option for a track: metadata + image URLs + a small
/// preview thumbnail. The full-resolution image is downloaded lazily when the
/// user picks this candidate (see `save_selected_artwork`).
struct ArtworkChoice {
    release_id: String,
    title: String,
    year: String,
    label: String,
    country: String,
    format: String,
    thumb_url: String,
    cover_image_url: String,
    thumb_png: Vec<u8>,
}

/// All candidate releases fetched for one track, awaiting the user's pick.
struct ArtworkChoices {
    id: Id,
    label: String,
    candidates: Vec<ArtworkChoice>,
}

/// An image file dropped onto a track row, awaiting the user's confirmation to
/// set it as that track's cover. Drives the cover-drop modal (a popup that asks
/// before writing anything). The image is decoded and re-encoded to PNG up front
/// so both the modal preview and the stored cover use validated bytes.
struct CoverDrop {
    /// The track the image was dropped on (the primary target).
    track_id: Id,
    /// "Artist — Title" of the target track, for the modal header.
    track_label: String,
    /// Album name of the target track, shown when offering to apply to mates.
    album: String,
    /// Source path of the dropped image (shown small in the modal).
    image_path: PathBuf,
    /// Re-encoded PNG of the full image — stored as the cover and embeddable.
    full_png: Vec<u8>,
    /// Re-encoded, downscaled PNG used as the table thumbnail.
    thumb_png: Vec<u8>,
    /// Decoded preview texture for the modal (built lazily on first draw).
    preview: Option<Tex>,
    /// Other tracks on the same album, each with a checkbox to also receive the
    /// cover. Cover-less mates are pre-checked; mates that already have art start
    /// unchecked so an existing cover isn't clobbered without an explicit tick.
    siblings: Vec<CoverSibling>,
}

/// One album-mate row in the cover-drop modal's "apply to these too" selector.
struct CoverSibling {
    id: Id,
    label: String,
    has_art: bool,
    selected: bool,
}

/// Result of a finished background artwork save: the picked track (`id`) and the
/// album-mates the same cover was copied onto (`also`, empty when not propagated).
/// The UI uses `also` to drop the stale cached thumbnails of overwritten siblings.
struct ArtSaveDone {
    id: Id,
    also: Vec<Id>,
}

/// Messages the worker thread can send back to the UI.
enum JobMsg {
    Status(String),
    /// Determinate progress for the running job: `done` of `total` items
    /// finished. Drives the status-bar progress bar.
    Progress {
        done: usize,
        total: usize,
    },
    Done(String),
    Failed(String),
    /// Per-item failures from a background job: `(item name, reason)`, with a
    /// `title` naming what was attempted (e.g. "Scan", "Write edits"). Sent just
    /// before `Done` whenever a job skipped or errored on any item, so the UI
    /// can show the user exactly what didn't go through and why.
    Failures {
        title: String,
        items: Vec<(String, String)>,
    },
    /// Candidate releases fetched for one track, for the user to pick from.
    ArtworkChoices(ArtworkChoices),
    /// The Discogs username resolved during a vinyl sync, so the UI can persist
    /// it (config) and link to the user's collection page.
    VinylUsername(String),
}

/// Result of a background full-resolution cover load. The decode (potentially a
/// multi-megapixel JPEG) happens off the UI thread; the main thread turns the
/// pixels into a texture. `image` is `None` when the track has no usable cover.
struct CoverLoaded {
    id: Id,
    image: Option<egui::ColorImage>,
    /// Set only for USB loads: the device listing the request was made against.
    /// `None` from the catalog loader, whose ids are stable rowids.
    usb_generation: Option<u64>,
}

/// Where a USB row's cover art comes from. Resolved on the UI thread (a map
/// lookup) and handed to the loader, so the worker never reaches into `App`
/// state that the UI thread is concurrently mutating.
enum UsbThumbSource {
    /// The file scan already extracted the embedded art.
    Embedded(Vec<u8>),
    /// Nothing scanned yet: the export's pre-extracted ARTWORK JPEG on the
    /// device stands in. This is the read that has to stay off the UI thread —
    /// it hits the stick.
    File(PathBuf),
}

/// One USB cover to load, with its source already resolved.
struct UsbThumbReq {
    id: Id,
    source: UsbThumbSource,
    /// Which device listing this was asked for. USB ids are `BASE + index`, so
    /// index 5 on the next stick reuses index 5's id on this one — without this
    /// an in-flight decode could land on an unrelated row after a swap.
    generation: u64,
}

/// Identity of one vinyl cover: which Discogs list it belongs to and that list's
/// row key (`instance_id` for the collection, `release_id` for the wantlist).
type VinylCoverKey = (VinylList, u64);

/// Result of a background vinyl cover decode, carrying the key that asked for it
/// so the collection and wantlist grids never cross wires.
struct VinylCoverLoaded {
    key: VinylCoverKey,
    image: Option<egui::ColorImage>,
}

/// One user-requested change to a Discogs list. Every variant writes to the
/// user's actual Discogs account and then mirrors the change into the local
/// cache, so the grid reflects it without waiting for a full sync. Built by the
/// vinyl grid's right-click menu and the library's "Add to Discogs wantlist",
/// then run off the UI thread by `run_vinyl_edit`.
#[derive(Debug, Clone)]
pub(crate) enum VinylEdit {
    /// Want these releases, named from the library rather than the grid — so
    /// there's no cached record yet and Discogs's response supplies the metadata.
    /// Carries a label for the status line, since the ids mean nothing to the user.
    Want {
        release_ids: Vec<u64>,
        label: String,
    },
    /// Move one cached record to the other list. Two Discogs calls (add to the
    /// destination, remove from the source), then one local re-key.
    Move {
        from: VinylList,
        record: Box<VinylRecord>,
    },
    /// Own one release, named by id rather than from a cached row — the record
    /// sheet's "Add to collection", which can be open on a record the user
    /// doesn't have yet (a dug one). Mirrors [`VinylEdit::Want`]: Discogs's
    /// response supplies the metadata to cache.
    Collect { release_id: u64, label: String },
    /// Drop one cached record from its list entirely.
    Remove {
        list: VinylList,
        record: Box<VinylRecord>,
    },
    /// Replace one cached record with a different pressing of the same record —
    /// the "hotswap" from the versions panel. Structurally a [`VinylEdit::Move`]
    /// that changes release rather than list: add `to_release` to the list the
    /// record is already in, then drop the old copy. Ordered that way so a
    /// failure leaves the user with both pressings rather than neither.
    Swap {
        list: VinylList,
        record: Box<VinylRecord>,
        to_release: u64,
        /// How to name the incoming pressing in the status line, since its id
        /// means nothing to the user.
        to_label: String,
    },
}

impl VinylEdit {
    /// Whether this edit destroys a collection copy on Discogs — its date added,
    /// rating and notes go with it, and Ordnung can't put them back. True for
    /// both an outright removal from the collection and a move out of it; those
    /// are the edits worth a confirmation step. Wantlist edits are cheap to undo
    /// (re-adding a want costs nothing but the release id), so they just run.
    pub(crate) fn destroys_collection_copy(&self) -> bool {
        matches!(
            self,
            VinylEdit::Move {
                from: VinylList::Collection,
                ..
            } | VinylEdit::Remove {
                list: VinylList::Collection,
                ..
            } | VinylEdit::Swap {
                list: VinylList::Collection,
                ..
            }
        )
    }
}

/// Result of a background "what would this release fill in?" lookup, computed for
/// the "Fetch song data" picker so the user can see the data before committing.
/// Carries the human-readable (field, value) rows to display and the underlying
/// `ReleaseDetail` to reuse on apply (so we don't fetch the release twice).
struct PreviewMsg {
    track_id: Id,
    release_id: String,
    /// Whether this preview was computed in overwrite mode — part of the cache
    /// key, so it must round-trip back from the worker.
    overwrite: bool,
    /// `(field label, value)` for each field this release would write under the
    /// current mode. Empty when the release adds nothing new or the lookup failed.
    fills: Vec<(String, String)>,
    /// `None` when the release lookup failed (network/decode).
    detail: Option<discogs::ReleaseDetail>,
}

/// What the Discogs settings tab knows about the saved token. "Connected" is
/// only ever reached by a real `GET /oauth/identity` round-trip — a token that
/// merely *exists* in the config proves nothing, since it may have been revoked
/// or mistyped, and the old UI surfaced that as a confusing mid-fetch failure.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub(crate) enum DiscogsAuth {
    /// No token saved (and none in `DISCOGS_TOKEN`).
    #[default]
    SignedOut,
    /// A token is saved but hasn't been checked yet this session.
    Unverified,
    /// Identity request in flight.
    Checking,
    /// Discogs confirmed the token and named its owner.
    Connected { username: String },
    /// Discogs rejected the token (HTTP 401/403) — revoked, mistyped, or wrong.
    Rejected,
    /// The check itself failed (offline, DNS, timeout). Distinct from
    /// [`DiscogsAuth::Rejected`]: the token may be perfectly good, so this must
    /// not read as "your token is bad".
    Unreachable { detail: String },
}

/// Category tabs in the Settings window's left rail (Ableton-style). Session-only
/// selection; the window always opens on the default ([`SettingsTab::General`]).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub(crate) enum SettingsTab {
    #[default]
    General,
    Analysis,
    Waveform,
    Sorting,
    Conversion,
    Discogs,
    Advanced,
}

impl SettingsTab {
    /// All tabs in rail order.
    pub(crate) const ALL: [SettingsTab; 7] = [
        SettingsTab::General,
        SettingsTab::Analysis,
        SettingsTab::Waveform,
        SettingsTab::Sorting,
        SettingsTab::Conversion,
        SettingsTab::Discogs,
        SettingsTab::Advanced,
    ];

    /// Label shown in the left rail.
    pub(crate) fn label(self) -> &'static str {
        match self {
            SettingsTab::General => "General",
            SettingsTab::Analysis => "Analysis",
            SettingsTab::Waveform => "Waveform",
            SettingsTab::Sorting => "Sorting",
            SettingsTab::Conversion => "Conversion",
            SettingsTab::Discogs => "Discogs",
            SettingsTab::Advanced => "Advanced",
        }
    }
}

/// A sidebar resize in progress. The panel stays locked to `NavDensity` while
/// the edge is held; this is only what the ghost line draws and what the drop
/// will commit.
#[derive(Clone, Copy)]
struct NavDrag {
    /// Live pointer x, in screen space — where the ghost line is painted.
    x: f32,
    /// The tier this drag would land on, run through the same hysteresis the
    /// commit uses so the ghost previews the real outcome rather than a plain
    /// nearest-match the drop would then disagree with.
    target: NavDensity,
}

struct App {
    db_path: PathBuf,
    rows: Vec<TrackRow>,
    filter: String,
    /// When a pending search-box edit should be applied, if any.
    ///
    /// Rebuilding the rows means re-querying the catalog for every track, so
    /// reloading on each keystroke made a typed word cost one full rebuild per
    /// character — all but the last of them thrown away before a frame ever showed
    /// them. Typing instead parks a deadline here and the reload happens once the
    /// user pauses (see `SEARCH_DEBOUNCE`).
    filter_apply_at: Option<std::time::Instant>,
    /// Ranked search suggestions for the current search box text, spanning the
    /// digital catalog and the vinyl collection/wantlist. Recomputed on the same
    /// debounce as the table filter; empty when the box is empty or the popup
    /// has been dismissed. See [`ordnung_core::search`].
    search_hits: Vec<ScoredHit>,
    /// What's typed in the toolbar search box.
    ///
    /// Deliberately *not* `filter`: typing searches, it doesn't filter. The box
    /// offers a ranked dropdown, and only picking a hit acts on the library —
    /// otherwise every keystroke on the way to "lawrence" tore the table down
    /// and rebuilt it around meaningless prefixes. `filter` is still the table's
    /// own filter, set when a hit is chosen (or by the vinyl grid's jump).
    search_query: String,
    /// When a parked search-box edit should rebuild the suggestions. Mirrors
    /// `filter_apply_at`, but for the dropdown rather than the table.
    search_apply_at: Option<std::time::Instant>,
    /// Whether the suggestion popup is showing. Separate from `search_hits`
    /// being non-empty so Esc (and picking a hit) can dismiss the popup without
    /// clearing the query the table is still filtered by.
    search_popup_open: bool,
    /// When the current `search_hits` list went on screen, used as the origin
    /// for the popup's staggered row entrance. Re-stamped whenever the results
    /// actually change (not on every keystroke), so refining a query replays the
    /// cascade while an unchanged list stays put. `None` while the popup is
    /// fully closed.
    search_row_shown_at: Option<std::time::Instant>,
    /// Set for one frame when ⌘F (or Edit ▸ Find) asks for the search box.
    /// The toolbar consumes it right after building the field — the request has
    /// to outlive the keypress by exactly that long, because the field's
    /// `Response` doesn't exist yet at the point the shortcut is read.
    focus_search: bool,
    /// Keyboard cursor within `search_hits`, driven by ↑/↓ in the search box.
    /// `None` means nothing is highlighted and Enter falls through to the plain
    /// filter behaviour.
    search_cursor: Option<usize>,
    /// Cover textures for the search popup's vinyl rows, keyed like
    /// `vinyl_covers`.
    ///
    /// Deliberately a *separate* cache: `vinyl_covers` is scoped to the Vinyl
    /// view and cleared by `reload` whenever another view is active (see
    /// `App::reload`), but the popup shows records from the Library view, where
    /// that cache is always empty. Sharing it would re-request every cover only
    /// to have the next reload drop it again. Bounded by the popup's 5 rows plus
    /// whatever earlier queries left behind, so it stays tiny.
    search_vinyl_covers: HashMap<VinylCoverKey, ThumbState>,
    search_cover_req_tx: Sender<VinylCoverKey>,
    search_cover_rx: Receiver<VinylCoverLoaded>,
    /// Which database the search box is pointed at — the local library or all
    /// of Discogs. Toggled by the control on the right of the field; see
    /// `records.rs` for why these are modes rather than one blended list.
    search_scope: SearchScope,
    /// State of the current Discogs lookup: idle, in flight, answered, or failed.
    record_search: RecordSearch,
    /// Monotonic id for lookup requests. A reply carrying anything other than
    /// the current value is a stale answer for a query the user has typed past,
    /// and is dropped on arrival.
    record_generation: u64,
    /// Queries already answered this session, so backspacing to a previous one
    /// is instant instead of costing another rate-limited request.
    record_cache: HashMap<String, (Vec<ordnung_core::discogs::RecordHit>, u32)>,
    record_tx: Sender<RecordFetched>,
    record_rx: Receiver<RecordFetched>,
    /// When a parked keystroke should fire the Discogs lookup. Separate from
    /// `search_apply_at` because a network lookup wants a much longer pause than
    /// the local suggestion rebuild.
    record_apply_at: Option<std::time::Instant>,
    /// The primary/active row — drives the inspector. Always the last row the
    /// user clicked (and a member of `selection` whenever `selection` is non-empty).
    selected: Option<Id>,
    /// Every selected row. Single click selects one; Cmd-click toggles; Shift-click
    /// extends a contiguous range. Drives the row highlight and which tracks a
    /// drag-out carries. Kept in sync with the visible `rows` on reload.
    selection: HashSet<Id>,
    /// Anchor row for Shift-click range selection (the last non-shift click).
    select_anchor: Option<Id>,
    /// Full Track (every tag) for the inspector panel — fetched on selection.
    selected_track: Option<Track>,
    /// Whether the selected track has full-resolution fetched artwork on record
    /// (drives the inspector's "embed cover into file" action). Refreshed with
    /// `selected_track`.
    selected_has_external_art: bool,
    convert_modal: Option<ConvertModal>,
    /// Open batch-convert dialog for the current selection, or `None`.
    batch_convert: Option<BatchConvert>,
    job_rx: Option<Receiver<JobMsg>>,
    status: String,
    /// Last status string we saw and the egui time (seconds) it appeared, used
    /// to fade an idle status message out of the bottom-left bar after a few
    /// seconds. Only idle messages expire; while a job runs the status stays.
    status_last: String,
    status_shown_at: f64,
    /// Determinate progress of the running job (`done`, `total`), or `None` when
    /// idle or running a job that doesn't report item counts. Drives the
    /// status-bar progress bar; cleared when the job finishes.
    progress: Option<(usize, usize)>,
    load_error: Option<String>,
    /// Decoded thumbnail textures keyed by track id. Lazy-populated for visible
    /// rows; see `ThumbState` for what each entry means. Reads (catalog + PNG
    /// decode) run on the `thumb` worker thread so scrolling never stalls.
    cover_cache: HashMap<Id, ThumbState>,
    /// Sends a track id to the persistent thumbnail worker, asking it to load and
    /// decode that row's small cover off the UI thread.
    thumb_req_tx: Sender<Id>,
    /// Request channel for USB row covers. Separate from `thumb_req_tx` because
    /// the source is a device path or scanned bytes, not a catalog id.
    usb_thumb_req_tx: Sender<UsbThumbReq>,
    /// Bumped every time `usb_tracks` is replaced; stamped on each USB cover
    /// request so results from a previous device are dropped on arrival.
    usb_generation: u64,
    /// Receives finished thumbnail decodes from the worker; drained each frame by
    /// `poll_thumbs`, which uploads the texture (a UI-thread-only op) and caches it.
    thumb_rx: Receiver<CoverLoaded>,
    /// Decoded *full-resolution* cover textures for the inspector preview, keyed
    /// by track id. Separate from `cover_cache` (the small table thumbnails) so
    /// the table stays cheap while the inspector shows high-quality art. Filled
    /// asynchronously: a `None` entry means "loaded, no cover"; a missing entry
    /// means "not loaded" (possibly in flight — see `cover_inflight`).
    cover_full_cache: HashMap<Id, CoverEntry>,
    /// Track ids whose full cover is currently decoding on a background thread.
    /// Prevents spawning duplicate loaders and drives the "loading…" placeholder.
    cover_inflight: HashSet<Id>,
    /// Shared parking lot behind every cached [`Tex`]: dropping a `Tex`
    /// anywhere parks its GPU texture here instead of freeing it mid-frame
    /// (which would panic wgpu — see `tex.rs` for the full story). Emptied at
    /// the top of each `update()`, once the frame that painted the parked
    /// textures has been submitted. Wrap every cached `ctx.load_texture`
    /// result with `self.tex_graveyard.wrap(...)`.
    tex_graveyard: TexGraveyard,
    /// Persistent channel for finished cover decodes. Loader threads clone the
    /// sender; the UI drains the receiver each frame and builds textures.
    cover_tx: Sender<CoverLoaded>,
    cover_rx: Receiver<CoverLoaded>,
    /// The user's cached Discogs vinyl collection, shown in the `Vinyl` grid view.
    /// Repopulated from the `vinyl_collection` table on every `reload`.
    vinyl: Vec<VinylRecord>,
    /// The user's cached Discogs wantlist — records they want but don't own —
    /// rendered as its own section below the collection in the same view.
    /// Repopulated from the `vinyl_wantlist` table alongside `vinyl`.
    wantlist: Vec<VinylRecord>,
    /// Count of cached vinyl records, for the sidebar label. Kept fresh on reload
    /// so the badge is right even when the grid isn't the active view.
    vinyl_count: u64,
    /// Which shelf the vinyl view is showing: the collection or the wantlist.
    /// They're two shelves of the same size, so they're tabs rather than one
    /// stacked scroll — with a big collection, the wantlist was a long way down.
    /// Not persisted: the view opens on what you own.
    vinyl_tab: VinylList,
    /// Free-text filter for the vinyl view's search bar. Narrows both shelves by
    /// artist, title, year and format as you type. Not persisted: a search is
    /// about the record you're looking for right now, not a saved view.
    vinyl_filter: String,
    /// Decoded vinyl cover textures keyed by list + Discogs `instance_id` (reuses
    /// `ThumbState`). Loaded lazily by the vinyl-cover worker as cells render,
    /// mirroring `cover_cache` for table rows. The list is part of the key because
    /// collection instance ids and wantlist release ids are separate id spaces.
    vinyl_covers: HashMap<VinylCoverKey, ThumbState>,
    /// Asks the vinyl-cover worker to load + decode one record's cached cover.
    vinyl_cover_req_tx: Sender<VinylCoverKey>,
    /// Finished vinyl-cover decodes. Drained each frame, uploaded to a texture,
    /// and cached under the same key that requested them.
    vinyl_cover_rx: Receiver<VinylCoverLoaded>,
    /// Discogs `release_id` → catalog track ids that link to it (via fetched
    /// artwork/metadata). Lets the vinyl grid flag records you already own a
    /// digital copy of and jump to them. Rebuilt with `vinyl` on reload.
    vinyl_links: HashMap<u64, Vec<Id>>,
    /// The reverse map: catalog track id → the Discogs `release_id` its artwork
    /// fetch settled on. Drives the library's "Add to Discogs wantlist" action,
    /// which is only offered for tracks that actually have a release to want.
    /// Rebuilt on every reload (one indexed scan of the artwork table).
    track_releases: HashMap<Id, u64>,
    /// Release ids already in the user's Discogs collection and wantlist. Used
    /// by the vinyl grid to spot a record sitting in both lists, where a move
    /// would ask Discogs for a duplicate copy.
    vinyl_owned: HashSet<u64>,
    vinyl_wanted: HashSet<u64>,
    /// The same membership seen from the library: catalog tracks whose record is
    /// already in the collection / wantlist. Matched the way the grid's "in
    /// catalog" badge matches — exact release id, then album/artist metadata —
    /// so a track that was never Discogs-fetched still knows the record is yours.
    /// Kept in every view so the library menu can answer without holding the
    /// full record lists the grid loads.
    vinyl_owned_tracks: HashSet<Id>,
    vinyl_wanted_tracks: HashSet<Id>,
    /// A pending Discogs list change awaiting confirmation, because it would
    /// destroy collection metadata on the user's account (see [`VinylEdit`]).
    /// `Some` shows the confirm modal; the edit only runs if they say yes.
    confirm_vinyl_edit: Option<VinylEdit>,
    /// The open record sheet — one record's tracklist, with what can play each
    /// position (a local file, a Discogs-listed YouTube video, or nothing).
    /// `None` when no record is open. See [`vinyl_sheet`].
    vinyl_sheet: Option<VinylSheet>,
    /// The open sheet is riding the dig: a thread was taken from the sheet's own
    /// branch buttons, so when the step lands the sheet re-points at the record
    /// the dig walked to instead of closing. Digging from the sheet is a chain
    /// of listens, and closing the window between each one would make the user
    /// chase the strip with the pointer to hear the next find. Cleared when the
    /// step lands, when it fails, or when the sheet closes.
    sheet_follows_dig: bool,
    /// Receives the release detail (tracklist + videos) fetched for the open
    /// sheet. One release per lookup, off the UI thread; results for a record
    /// the user has since closed are dropped.
    sheet_rx: Option<Receiver<SheetFetched>>,
    /// Receives the open sheet's marketplace price lookup, as
    /// `(release_id, result)` so a reply for a record the user has since closed
    /// is dropped rather than shown against the wrong record.
    #[allow(clippy::type_complexity)]
    sheet_price_rx: Option<
        Receiver<(
            u64,
            ordnung_core::Result<(
                Option<discogs::MarketPrice>,
                Option<(discogs::MasterVersion, discogs::MarketPrice)>,
            )>,
        )>,
    >,
    /// The open "other pressings" panel — every release hanging off the same
    /// Discogs master as one record, and the swap that trades your copy for one
    /// of them. `None` when it isn't open. See [`versions`].
    versions: Option<versions::VersionsPanel>,
    /// Receives the sibling-pressing lookup for the open versions panel. Tagged
    /// with the release it was asked for, so a reply for a panel the user has
    /// since closed or re-pointed is dropped.
    versions_rx: Option<Receiver<versions::VersionsFetched>>,
    /// A clone of the egui context, so background work started from a place
    /// that isn't handed one (the dig's browse and cover fetches) can still ask
    /// for a repaint when it lands.
    egui_ctx: egui::Context,
    /// The dig in progress above the vinyl grid — the path of records walked by
    /// following artist and label threads, and where along it the user is.
    /// `None` when no dig is running, which is the view's normal state. See
    /// [`dig`].
    dig: Option<DigPath>,
    /// Rolling seed for the dig's random pick. Advanced every frame the strip
    /// draws, so taking the same branch twice from one record lands somewhere
    /// else rather than repeating.
    dig_seed: u64,
    /// Receives a dug release's Discogs artist and label ids, which are what its
    /// own two branches browse by. `(release_id, (artist_ids, label_ids))`.
    dig_ids_rx: Option<Receiver<(u64, (Vec<u64>, Vec<u64>, Option<String>))>>,
    /// Receives the finished Discogs browse for the step being dug.
    dig_rx: Option<Receiver<dig::DigFetched>>,
    /// Receives speculative browses for the two threads out of the record on
    /// screen, fetched ahead of the click that takes one. A persistent channel
    /// rather than a one-shot `Option<Receiver>`: one prefetch worker delivers
    /// two results, and a result for a record the user has already left still
    /// has to be received so it can be dropped. See [`dig`].
    dig_prime_tx: Sender<dig::DigPrimed>,
    dig_prime_rx: Receiver<dig::DigPrimed>,
    /// Covers for dug records, keyed by thumbnail URL rather than by list +
    /// instance id: these records aren't in either list, so they have no local
    /// cache entry to key against.
    dig_covers: HashMap<String, ThumbState>,
    dig_cover_tx: Sender<(String, Option<egui::ColorImage>)>,
    dig_cover_rx: Receiver<(String, Option<egui::ColorImage>)>,
    /// Cover-cache keys for the records digs were started from, so the strip can
    /// draw the one step that *is* in a list from the local cache.
    dig_start_keys: HashMap<u64, VinylCoverKey>,
    /// A track the table should scroll to and reveal on the next frame, set when
    /// jumping into the catalog from the vinyl grid. Cleared once honoured.
    scroll_to_track: Option<Id>,
    /// Screen-space rect of each visible table row this frame, with its track id.
    /// Filled in `draw_table` and read by `handle_file_drop` to map a dropped
    /// image onto the row under the cursor. Rebuilt every frame.
    row_screen_rects: Vec<(Id, egui::Rect)>,
    /// An image dropped onto a track row, awaiting confirmation to set it as that
    /// track's cover. `Some` shows the cover-drop modal. See [`CoverDrop`].
    cover_drop: Option<CoverDrop>,
    /// Whether the inspector's tag block is in edit mode. Off by default: the
    /// fields render as plain read-only rows, so the panel reads as a summary
    /// instead of a wall of text boxes. The "Edit" toggle turns them into inputs.
    tags_editing: bool,
    /// Set while a cancellable job (scan / artwork fetch) is running; the worker
    /// polls it and stops early. `None` when idle or running a non-cancellable job.
    job_cancel: Option<Arc<AtomicBool>>,
    /// Per-track candidate releases waiting for the user to pick (front first).
    artwork_queue: VecDeque<ArtworkChoices>,
    /// Whether picking a candidate should also fill in the track's missing
    /// album-level tag fields from the chosen release ("Fetch song data" button),
    /// or just cache the cover ("Fetch artwork" button — harmless, no tag edits).
    /// Set when the fetch run is launched; read when a candidate is saved.
    artwork_enrich: bool,
    /// Tracks whose Discogs release is being fetched *so it can be wantlisted*:
    /// the library menu's "Add to Discogs wantlist" on an unmatched selection
    /// opens the release picker first, then adds whatever it settled on. Drained
    /// once the picker queue empties (whether the user picked, skipped or
    /// cancelled) — only the tracks that ended up with a release get wanted.
    /// The label names the selection in the status line.
    wantlist_after_fetch: Vec<Id>,
    wantlist_after_fetch_label: String,
    /// Release ids from the same "add to wantlist" request that were already
    /// matched — held aside so they're wanted in the same edit as the ones the
    /// picker is still resolving.
    pending_wantlist_releases: Vec<u64>,
    /// In a song-data run, whether committing a release *replaces* existing tag
    /// values (true) or only fills empty ones (false, the default). Toggled by a
    /// checkbox in the picker; read when a candidate is saved and woven into the
    /// field preview so what's shown matches what gets written.
    artwork_overwrite: bool,
    /// In a song-data run, whether committing the chosen release also sets the
    /// track's cover from it. Defaulted per front track when the picker advances:
    /// off when the track already has art (so enriching tags never clobbers an
    /// existing cover), on when it has none. Toggled by a checkbox in the picker;
    /// read when a candidate is saved. The "Fetch artwork" run ignores this — there
    /// the cover *is* the point and is always written.
    artwork_set_cover: bool,
    /// Whether saving the chosen cover should also copy it to the front track's
    /// album-mates. One lookup then dresses a whole album. Toggled by a checkbox in
    /// the picker that only appears when album-mates exist; read when a candidate
    /// is saved.
    artwork_apply_album: bool,
    /// Within an "apply to album" save, whether to also *overwrite* album-mates
    /// that already have their own cover (true → every album-mate matches), or
    /// only fill the cover-less ones (false, the safe default).
    artwork_album_overwrite: bool,
    /// Cached album-mate counts for the front track — `(id, missing, total)` where
    /// `missing` is cover-less mates and `total` is all mates. Keyed by id so the
    /// DB is queried once per track, not every frame. Drives the checkbox labels
    /// and which controls appear.
    artwork_album_count: Option<(Id, usize, usize)>,
    /// Cached album-mate details for the front track of the artwork picker —
    /// `(id, [(id, label, has_art)])`. Computed once per front track (alongside
    /// `artwork_album_count`) so the picker can list *which* songs share the
    /// chosen cover by name, not just a count.
    artwork_album_siblings: Option<(Id, Vec<(Id, String, bool)>)>,
    /// Index of the currently highlighted candidate for the front track.
    artwork_selected: usize,
    /// Decoded preview thumbnails for the front track's candidates, keyed by
    /// track id so we only re-decode when the front track changes.
    artwork_previews: Option<(Id, Vec<Option<Tex>>)>,
    /// True while the chosen cover's full-resolution image is downloading and
    /// being written on a background thread. Drives the Save button's spinner
    /// and blocks the picker's controls so the front track can't change until
    /// the save lands.
    artwork_saving: bool,
    /// Channel carrying a finished background artwork save (the picked track plus
    /// any album-mates the cover was propagated to). The saver thread clones the
    /// sender; the UI drains the receiver each frame to advance the queue and
    /// refresh caches once the save has actually landed.
    art_save_tx: Sender<ArtSaveDone>,
    art_save_rx: Receiver<ArtSaveDone>,
    /// Channel for finished "Fetch song data" field previews (which fields a
    /// candidate release would fill). Worker threads clone the sender; the UI
    /// drains the receiver each frame into `preview_cache`.
    preview_tx: Sender<PreviewMsg>,
    preview_rx: Receiver<PreviewMsg>,
    /// Computed field previews keyed by `(track id, release id, overwrite)`: the
    /// `(label, value)` rows shown in the song-data picker. The `overwrite` flag
    /// is part of the key because it changes which fields a release would write.
    /// An entry means the lookup finished (possibly with zero rows); absence
    /// means "not loaded".
    preview_cache: HashMap<(Id, String, bool), Vec<(String, String)>>,
    /// `(track id, release id, overwrite)` previews currently being fetched, so
    /// we don't spawn duplicate lookups and can show a spinner while one runs.
    preview_inflight: HashSet<(Id, String, bool)>,
    /// Fetched `ReleaseDetail`s keyed by release id, kept so applying a chosen
    /// release reuses the preview's fetch instead of hitting Discogs again.
    release_detail_cache: HashMap<String, discogs::ReleaseDetail>,
    /// Persistent settings (Discogs token), loaded from `~/.ordnung/config.toml`.
    config: Config,
    /// Visible-and-hidden track-table columns in left-to-right order, reordered
    /// via the header right-click menu and persisted to config. Always a
    /// permutation of `TableColumn::DEFAULT_ORDER`; entries in `hidden_columns`
    /// keep their slot here (so re-showing restores their position) but aren't
    /// drawn.
    column_order: Vec<TableColumn>,
    /// Columns hidden via the reorder menu — not drawn, but still listed in the
    /// menu so they can be brought back.
    hidden_columns: HashSet<TableColumn>,
    /// User-resized track-table column widths (points), keyed by column. Shared
    /// across every view and persisted to config so a resize in one playlist
    /// applies everywhere and survives rebuilds. Absent columns use their default
    /// width. Mirrors `config.column_widths`; the table reads it to seed each
    /// column and writes observed widths back after a resize.
    column_widths: HashMap<TableColumn, f32>,
    /// Set when `column_widths` changed this frame from a live resize; the new
    /// widths are flushed to config once the drag ends (pointer released) so a
    /// drag doesn't rewrite the TOML on every frame.
    column_widths_dirty: bool,
    /// Set by "Reset to default" in the column menu; consumed by the next table
    /// build to also clear egui_extras' own stored widths (which otherwise
    /// override the freshly-cleared defaults until a rebuild).
    reset_column_widths: bool,
    /// When `Some`, the column reorder popup is open, anchored at this screen
    /// position (where the header was right-clicked).
    column_menu: Option<egui::Pos2>,
    /// Per-column "filter by this column's values" text, keyed by column. Set
    /// from the popup opened by double-clicking a header; an absent or empty
    /// entry means that column isn't filtering. Applied in-memory over the
    /// loaded rows (on top of the global `filter`), so it composes with the
    /// global search and the active sort.
    col_filters: HashMap<TableColumn, String>,
    /// When `Some`, the per-column filter search bar is open (a header was
    /// double-clicked); mirrors `column_menu`.
    col_filter_open: Option<ColFilterPopup>,
    /// Whether the inspector side panel is showing. Toggled by the pull tab at
    /// the window's right edge — the panel is a fixed-width drawer that slides
    /// in and out rather than a splitter the user drags to size.
    inspector_open: bool,
    /// Whether the native macOS menu bar has been installed yet. It goes up on
    /// the first frame rather than at construction, because the `NSApplication`
    /// it attaches to doesn't exist until eframe has started (see `macos_menu`).
    menu_installed: bool,
    /// The first-run welcome tour, when it's showing. `None` once finished or
    /// dismissed; see [`onboarding`] for why it owns the writeback choice.
    tour: Option<Tour>,
    /// Whether the Settings window is open.
    settings_open: bool,
    /// Which category tab is active in the Settings window. Session-only — the
    /// window always opens on the default tab; not persisted to config.
    settings_tab: SettingsTab,
    /// Edit buffer for the token field while the Settings window is open.
    token_input: String,
    /// Result of the last Discogs identity check — what the Discogs settings tab
    /// renders. Verified against `GET /oauth/identity`, so it reflects whether
    /// the saved token *actually works*, not merely that one is present.
    discogs_auth: DiscogsAuth,
    /// Delivers the identity check's outcome from its worker thread.
    discogs_auth_rx: Option<Receiver<DiscogsAuth>>,
    /// Whether the "clear the whole catalog?" confirmation popup is showing.
    confirm_clear_db: bool,
    /// USB export pending confirmation. The modal either spawns the export
    /// job or clears this.
    export_confirm: Option<ExportConfirm>,
    /// Title of the failure report (which job produced it).
    failure_report_title: String,
    /// Per-item failures `(item name, reason)` from the last job that had any.
    /// Drives the failure-report popup; empty when nothing failed.
    failure_report: Vec<(String, String)>,
    /// Whether the failure-report popup is open.
    show_failure_report: bool,
    /// Audio output for the cover snippet-preview button. `None` if the machine
    /// has no usable output device (the button is then hidden).
    audio: Option<AudioEngine>,
    /// Carries the now-playing track's resolved cover (a `file://` temp-file URL,
    /// or `None`) back from the off-thread loader so the OS Now Playing panel can
    /// show artwork. Tagged with the track `Id` to ignore stale results.
    media_cover_tx: Sender<(Id, Option<String>)>,
    media_cover_rx: Receiver<(Id, Option<String>)>,
    /// Carries the high-res zoom-waveform envelope (`[low,mid,high,loud]` bytes)
    /// back from the off-thread analysis of the playing track's PCM, tagged with
    /// the track `Id` so stale results are dropped. See [`player::compute_hires_bands`].
    hires_tx: Sender<(Id, Vec<u8>)>,
    hires_rx: Receiver<(Id, Vec<u8>)>,
    /// Live edit buffers for the inspector's editable Core fields (current
    /// selection). Repopulated whenever the selection changes or a save lands.
    tag_edit: TagEdit,
    /// Snapshot of `tag_edit` as last loaded/saved; `tag_edit != tag_edit_saved`
    /// means there are unsaved edits (drives the Save / Write button state).
    tag_edit_saved: TagEdit,
    /// Cached count of tracks with catalog edits not yet written to their source
    /// files (`user_edited`). Refreshed on every `reload`; drives the toolbar's
    /// bulk "write edits to files" button label and enabled state.
    edited_count: u64,
    /// Cached count of tracks whose source file is missing from disk. Refreshed
    /// after jobs and on Refresh (not on every filter keystroke — file existence
    /// doesn't change with the filter). Drives the toolbar's "relocate missing"
    /// button, which only appears when this is non-zero.
    missing_count: u64,
    /// How many tracks sit in the "recently added" inbox — fresh imports not yet
    /// both analyzed and song-data fetched. Refreshed on every `reload` (it's a
    /// cheap count) so the sidebar's Recent badge stays live as tracks expire out
    /// of the view. See [`LibraryView::RecentlyAdded`].
    recent_count: u64,
    /// Track ids currently pinned into the [`LibraryView::RecentlyAdded`] table:
    /// the rows shown the last time it was loaded while the tab was open. A track
    /// that finishes (analyzed + fetched) while you're looking at Recent stays
    /// here so it doesn't vanish mid-glance; the set is cleared when you leave the
    /// tab, so re-entering recomputes the live inbox and the finished track drops
    /// off. Empty whenever the Recent tab isn't the active view.
    recent_pinned: HashSet<Id>,
    /// "Artist — Title" labels for the missing tracks, refreshed alongside
    /// `missing_count`. Drives the relocate button's hover list so it works from
    /// any view (unlike `missing_list`, which only fills in the Missing view).
    missing_labels: Vec<String>,
    /// Whether the "write N edited tracks to their files?" confirmation is open.
    confirm_bulk_write: bool,
    /// Track ids pending a "delete from catalog?" confirmation, if that dialog is
    /// open. `Some` shows the modal; confirming deletes them from the catalog.
    confirm_delete: Option<Vec<Id>>,
    /// True while a bulk write-edits job is the active worker. Lets the job's
    /// completion handler drop cover textures, since that job may have embedded
    /// fetched art and the per-id texture cache would otherwise show stale covers.
    write_edits_running: bool,
    /// Set to the destination volume while a USB export job runs. When the job
    /// finishes, its completion handler forces a re-scan of that stick (by
    /// clearing `usb_loaded_for`) so the freshly written playlists appear in
    /// the device view without the user having to rescan or restart the app.
    export_running_to: Option<PathBuf>,
    /// Backstop for auto-write (`config.auto_write_tags`): the pending-edit count
    /// left over after an automatic write finished. Tracks whose files can't be
    /// written (read-only, missing, unsupported container) keep their
    /// `user_edited` flag, so without this the update loop would respawn the job
    /// every frame forever. Auto-write stands down until the count *changes* —
    /// a fresh edit, or the user clearing the stuck ones by hand.
    auto_write_stalled_at: Option<u64>,
    /// True when the running write-edits job was started by auto-write rather
    /// than the toolbar button. Read once the job finishes and the row counts
    /// have been refreshed, to decide whether to arm `auto_write_stalled_at`.
    auto_write_job: bool,
    /// Set when an auto-write job finished and the stall check is owed, cleared
    /// once the post-job reload has refreshed `edited_count`.
    auto_write_pending_latch: bool,
    /// Playlists & folders, refreshed on every `reload`. Drives the left sidebar.
    playlists: Vec<Playlist>,
    /// Duplicate groups for the Duplicates view. Computed off the UI thread (the
    /// acoustic-fingerprint scan is a full-catalog pass and would otherwise freeze
    /// the frame on click) and cached here between scans. Drives `draw_duplicates`.
    dup_groups: Vec<DuplicateGroup>,
    /// Set when the cached `dup_groups` may be stale and a rescan is wanted — on
    /// entering the view, an explicit Recompute, or a catalog mutation. A pending
    /// scan is kicked off from `update` (which has the egui `Context` the worker
    /// needs to wake the UI); coalesced so reload bursts spawn at most one rescan.
    dup_dirty: bool,
    /// A background duplicate scan is in flight. Gates re-spawning and drives the
    /// view's "Scanning…" spinner. The result arrives over `dup_rx`.
    dup_loading: bool,
    /// Receives the finished duplicate groups from the background scan worker.
    dup_rx: Option<std::sync::mpsc::Receiver<Vec<DuplicateGroup>>>,
    /// Per-copy keep/delete decisions in the Duplicates view, keyed by track id —
    /// `true` means "marked for deletion". Each group is seeded the first time it
    /// appears (best copy kept, the rest marked) and the user revises the marks
    /// before committing; entries for copies no longer in any group are pruned on
    /// every render. The "Delete N marked" button commits every `true` entry in
    /// one background pass. Reviewing is pure state — no disk IO — so marking
    /// never blocks.
    dup_decisions: HashMap<Id, bool>,
    /// A staged "delete the marked copies" batch awaiting confirmation. Holds the
    /// marked copies `(keeper id, drop id, source path)` to trash — the keeper is
    /// the kept copy in each group, which inherits the dropped copy's playlist
    /// slots. Confirming hands the batch to a background job. `None` when no batch
    /// is pending.
    dup_pending_bulk: Option<Vec<(Id, Id, PathBuf)>>,
    /// Screen position of the click that staged the pending duplicate
    /// delete/bulk, so the confirmation modal opens right under the cursor
    /// instead of dead-center (no mouse swipe to reach the confirm button).
    /// `None` falls back to a centered modal.
    dup_confirm_pos: Option<egui::Pos2>,
    /// Tracks whose source file is gone, for the Missing files view. Recomputed on
    /// `reload` while that view is active (empty otherwise). Drives `draw_missing`.
    missing_list: Vec<Track>,
    /// Which Library Health tab (Duplicates or Missing — the two share one window
    /// and one sidebar entry) was last open, so reopening the section returns to
    /// where the user left it. Always one of those two views.
    health_tab: LibraryView,
    /// Missing tracks the user clicked "Remove" on, awaiting confirmation. Holds the
    /// row ids to drop from the catalog (their files are already gone — removal never
    /// touches a real file). `None` when no confirmation is pending.
    missing_pending_remove: Option<Vec<Id>>,
    /// Mounted removable volumes for the sidebar's DEVICES section. Re-detected
    /// every couple of seconds (a cheap `/Volumes` readdir) so plugging or
    /// pulling a stick updates the sidebar live. See [`App::poll_usb`].
    usb_volumes: Vec<ordnung_core::usb::UsbVolume>,
    /// `ctx.input().time` of the last volume re-detection, throttling the poll.
    usb_last_poll: f64,
    /// Tracks found on the viewed USB volume — scanned off-thread straight from
    /// the device (these are NOT catalog tracks and have no ids). Kept while
    /// the volume stays mounted (so tab-hopping doesn't re-scan the stick);
    /// cleared when it's pulled.
    usb_tracks: Vec<ScannedTrack>,
    /// Per-track analysis summary lifted from the stick's `export.pdb` — the
    /// tempo and key rekordbox itself analyzed — keyed by index into
    /// `usb_tracks`. Empty for plain (non-rekordbox) sticks.
    usb_pdb_info: HashMap<usize, UsbPdbInfo>,
    /// Which volume `usb_tracks` was scanned from, so switching volumes (or an
    /// explicit Rescan setting this to `None`) triggers a fresh scan.
    usb_loaded_for: Option<PathBuf>,
    /// Playlist tree read from the volume's rekordbox `export.pdb` (empty for
    /// plain sticks). Drives the sidebar tree under the active device.
    usb_playlists: Vec<ordnung_rbdb::pdb::RbPlaylist>,
    /// Playlist id → indices into `usb_tracks`, in playlist order. Resolved by
    /// the scan worker (pdb paths matched to scanned files case-insensitively).
    usb_playlist_tracks: HashMap<u32, Vec<usize>>,
    /// A background USB scan is in flight; drives the view's spinner and gates
    /// re-spawning. The result arrives over `usb_rx` tagged with its volume.
    usb_loading: bool,
    /// Receives the finished device scan from the background USB scan worker.
    usb_rx: Option<std::sync::mpsc::Receiver<UsbScan>>,
    /// Receives the result message of a background `diskutil eject`, surfaced
    /// in the status bar (ejecting can fail, e.g. Finder holding a file open,
    /// and a silent failure looks like a broken button). `None` when idle.
    usb_eject_rx: Option<std::sync::mpsc::Receiver<String>>,
    /// BPM/key Ordnung analyzed itself for device files the stick's pdb and
    /// tags left blank, keyed by source path (indices shift between the pdb
    /// view and the file scan; paths don't). Filled by the auto-analysis
    /// worker `poll_usb` spawns after a device scan lands; kept while the
    /// volume stays mounted, cleared when it's pulled.
    usb_analysis: HashMap<String, UsbAnalyzed>,
    /// Receives per-track results from the USB auto-analysis worker. `None`
    /// when no analysis is running; the channel closing marks the run done.
    usb_analysis_rx: Option<std::sync::mpsc::Receiver<UsbAnalyzed>>,
    /// Progress of the running USB auto-analysis (done, total) for the status
    /// bar; zeroed when idle.
    usb_analysis_progress: (usize, usize),
    /// Cancels the in-flight USB auto-analysis (volume pulled, new scan).
    usb_analysis_cancel: Option<Arc<AtomicBool>>,
    /// Which of the sidebar's three width tiers is in force. The panel snaps
    /// between designed layouts instead of resizing freely, so this — not a
    /// pixel width — is the resize state, and it persists via
    /// `Config::nav_density`.
    nav_density: NavDensity,
    /// Where the resize pointer is while the sidebar edge is held, and the tier
    /// it would land on. `Some` only during a drag. The panel itself does *not*
    /// follow this — committing a tier mid-drag is what made labels wrap and
    /// unwrap under the pointer — so the live position is drawn as a ghost line
    /// instead and the tier is applied once, on release.
    nav_drag: Option<NavDrag>,
    /// Which track set the table shows — the whole library or one playlist.
    view: LibraryView,
    /// Inline rename in progress for a sidebar entry, or `None` when no row is
    /// being edited.
    renaming: Option<Renaming>,
    /// Active table sort: which column and direction (`true` = ascending).
    /// `None` keeps the natural order (catalog order, or the playlist's manual
    /// order). Set by clicking a column header.
    sort: Option<(SortColumn, bool)>,
    /// Display info for the track in the bottom now-playing bar — title/artist and
    /// the source path (used to lazily load its cover). Set when playback starts;
    /// the bar is shown while the engine still has this track loaded or decoding.
    now_playing: Option<NowPlaying>,
    /// A native drag-out started this frame from the now-playing bar's artwork,
    /// holding the playing track's source file. `draw_player` runs long before
    /// the frame's `begin_file_drag` dispatch, so the path parks here and is
    /// taken alongside the table's own drag (see `update`).
    player_native_drag: Option<PathBuf>,
    /// Fraction `[0, 1]` the user is dragging the scrubber to, before release. The
    /// actual seek fires on release so we rebuild the audio sink once, not per
    /// frame; `None` when not scrubbing.
    scrub: Option<f32>,
    /// Set while the volume knob is being dragged, so the config is written once
    /// on release rather than on every frame of the gesture.
    volume_dirty: bool,
    /// Seconds of audio visible in the zoomed detail lane above the overview
    /// strip. Adjusted by scrolling the wheel over the lane; the window centers on
    /// the playhead and scrolls under it during playback. See [`player`].
    wave_zoom_secs: f32,
    /// Pixel height of the moving zoomed detail lane. Dragged taller via the grip
    /// handle above the lane; the bottom player panel grows to match. See
    /// [`player`].
    wave_lane_h: f32,
    /// The zoom lane's beatgrid editor is open — its tab is lit, its panel of
    /// nudge controls shows above the lane, and dragging the lane slides the grid
    /// instead of seeking. See [`player`].
    grid_edit_open: bool,
    /// A nudge button in the beatgrid editor is being held down, so its repeats
    /// are moving the grid live. The catalog write is deferred until the release
    /// (one write per gesture, not one per repeat tick). See [`player`].
    grid_nudge_held: bool,
    /// Receives the one-shot startup update check's result off the network
    /// thread. `Some(info)` → a newer release exists; `None` → up to date or the
    /// check failed (we stay silent). Consumed once in `update()`, then dropped.
    update_rx: Option<Receiver<Option<ordnung_core::update::UpdateInfo>>>,
    /// A published release newer than this build, surfaced as a dismissible
    /// banner above the toolbar until the user downloads or dismisses it.
    update_available: Option<ordnung_core::update::UpdateInfo>,
}

/// What the bottom player bar needs to render the current track.
struct NowPlaying {
    id: Id,
    artist: String,
    title: String,
    /// Album tag captured alongside artist/title; empty when unknown. Lets the
    /// bar's title click jump to an album filter without a catalog read.
    album: String,
    source_path: String,
    /// Per-bin peak envelope (`Analysis::waveform_preview`), drives bar heights.
    /// Empty when the track isn't analyzed yet — the bar falls back to a line.
    ///
    /// These three envelopes are `Arc`ed because `draw_player` hands them to the
    /// panel closure every frame (the closure mutably borrows `self.scrub`, so it
    /// can't also borrow `self.now_playing`). Cloning the `Vec`s there meant
    /// memcpying the hi-res buffer — ~2.9 MB for a 6-minute track — at the display's
    /// refresh rate; an `Arc` clone is a refcount bump.
    waveform: Arc<Vec<u8>>,
    /// Per-bin `[low, mid, high]` band energy (`Analysis::waveform_bands`), drives
    /// the colour. Empty for pre-v10 analyses; colouring then degrades gracefully.
    waveform_bands: Arc<Vec<u8>>,
    /// High-resolution `[low, mid, high, loudness]` bands (same 4-byte stride as
    /// `waveform_bands`) computed once from the decoded PCM the engine holds — far
    /// finer than the stored ~20/sec preview, so the zoom lane shows rekordbox-level
    /// transient detail. `None` until the samples are available (still decoding).
    hires_bands: Option<Arc<Vec<u8>>>,
    /// Set once the off-thread hi-res analysis has been kicked off, so we don't
    /// respawn it every frame while it runs (or the PCM is still decoding).
    hires_requested: bool,
    /// Detected beatgrid for the moving lane's beat lines. `None` for unanalyzed
    /// tracks or ones with no confident tempo.
    grid: Option<PlayerGrid>,
}

/// The constant-tempo beatgrid the player overlays on the zoom lane. Beats are at
/// `first_beat_ms + i·(60000/bpm)`; beat `i` is a downbeat (bar "1") when
/// `(i - downbeat_phase).rem_euclid(4) == 0`.
#[derive(Clone, Copy)]
struct PlayerGrid {
    bpm: f32,
    first_beat_ms: f64,
    /// Index of the first downbeat within the beat run (0..3).
    downbeat_phase: u32,
}

/// Everything one background USB device scan produces: the audio files found
/// on the volume, and — when it carries a rekordbox export — the export's
/// playlist tree with each playlist's tracks already resolved to indices into
/// `tracks`. Tagged with the volume so a stale scan can't fill the wrong view.
struct UsbScan {
    vol: PathBuf,
    tracks: Vec<ScannedTrack>,
    playlists: Vec<ordnung_rbdb::pdb::RbPlaylist>,
    playlist_tracks: HashMap<u32, Vec<usize>>,
    /// Index into `tracks` → what the stick's own `export.pdb` says rekordbox
    /// analyzed for that file. See [`UsbPdbInfo`].
    pdb_info: HashMap<usize, UsbPdbInfo>,
    /// Whether this is the final result. A rekordbox stick sends two scans:
    /// an instant one built from `export.pdb` alone (the CDJ path — rows in
    /// milliseconds, nothing decoded), then the full file scan that enriches
    /// them with real tags and embedded art. `false` marks the first.
    complete: bool,
}

/// The analysis summary a rekordbox export carries per track — what the
/// player itself displays. Used to fill the table's BPM/Key columns for
/// device rows without decoding any audio.
#[derive(Debug, Clone, Default)]
struct UsbPdbInfo {
    /// Tempo from the pdb track row (already ÷100), when analyzed.
    bpm: Option<f32>,
    /// Key name from the pdb Keys table, in whatever notation rekordbox
    /// exported ("Am", "8A", "1d", …).
    key: Option<String>,
    /// The pre-extracted cover JPEG under `PIONEER/ARTWORK`, absolute on the
    /// mounted volume — how a CDJ shows art without touching the audio file.
    artwork_path: Option<PathBuf>,
    /// 400-bin amplitude preview read from the stick's own ANLZ files —
    /// the same waveform the player draws, shown without decoding audio.
    waveform: Vec<u8>,
    /// `[low, mid, high, loud]` quads at 20 bins/sec from the ANLZ color
    /// waveform; empty when the stick carries no `.EXT`.
    waveform_bands: Vec<u8>,
    /// The track's `ANLZ0000.DAT`, absolute on the mounted volume — read
    /// lazily for the pieces only playback needs (the beatgrid lane).
    anlz_path: Option<PathBuf>,
}

/// One device file's BPM/key as analyzed by Ordnung's own engine — the
/// automatic fallback for USB rows where neither the stick's `export.pdb` nor
/// the file's tags carry them. Never written anywhere: device files aren't
/// catalog rows, so this lives only in `App::usb_analysis` for the session.
#[derive(Debug, Clone)]
struct UsbAnalyzed {
    path: String,
    bpm: Option<f32>,
    key: Option<ordnung_core::model::key::Key>,
    /// Analyzer waveforms for sticks whose ANLZ files carry none — so device
    /// rows draw like library rows either way.
    waveform: Vec<u8>,
    waveform_bands: Vec<u8>,
}

/// USB tracks aren't catalog rows, but the shared table needs an `Id` per row.
/// Synthesize ids far above any real SQLite rowid so the two spaces can never
/// collide; catalog lookups on these simply miss (no analysis, no covers).
const USB_ID_BASE: Id = 1 << 62;

fn usb_track_id(index: usize) -> Id {
    USB_ID_BASE + index as Id
}

/// Inverse of [`usb_track_id`]: the `usb_tracks` index behind a synthetic id.
fn usb_track_index(id: Id) -> Option<usize> {
    id.checked_sub(USB_ID_BASE).map(|i| i as usize)
}

/// State for the inline text box that names a sidebar playlist.
struct Renaming {
    /// The playlist (or folder) being edited.
    id: Id,
    /// True when `id` names a node of the mounted device's rekordbox tree
    /// rather than a catalog playlist — the two id spaces are unrelated, so
    /// the editor must know which tree it belongs to.
    usb: bool,
    /// Live edit buffer bound to the `TextEdit`.
    buf: String,
    /// True when the row was just created, so an empty/cancelled edit removes it
    /// instead of leaving a blank placeholder behind.
    is_new: bool,
    /// Set on the frame the editor appears so we grab focus exactly once. If we
    /// re-requested focus every frame the box could never lose focus, so
    /// clicking away to commit/cancel would be impossible.
    needs_focus: bool,
}

/// A catalog-mutating request raised by the left sidebar, applied after the
/// panel closure ends so it doesn't borrow `self` while the tree is rendering.
enum SidebarAction {
    /// Create a playlist under the given parent folder (`None` = top level).
    NewPlaylist(Option<Id>),
    Rename(Id, String),
    Delete(Id),
    /// Tracks dropped onto a playlist (playlist id, dragged track ids).
    AddTracks(Id, Vec<Id>),
    /// Open the Library Health window on whichever tab was last used.
    OpenHealth,
    /// Device rows dropped on the Library source tab: copy their files into
    /// the library and import them.
    ImportUsbTracks(Vec<Id>),
    /// Right-click on a local playlist/folder: export it (and, for a folder,
    /// its descendants) to the given mounted volume as a rekordbox stick.
    ExportPlaylist(Id, PathBuf),
    /// Right-click on a local playlist: save its track list as a text file.
    SavePlaylistText(Id),
    /// Create a playlist on the mounted device, under the given rekordbox
    /// folder id (`0` = top level). Written straight to the stick's export.
    NewUsbPlaylist(u32),
    /// Rename a playlist/folder on the mounted device.
    RenameUsbPlaylist(u32, String),
    /// Delete a playlist (or folder and its subtree) on the mounted device.
    DeleteUsbPlaylist(u32),
    /// Device tracks dropped onto one of the device's own playlists: append
    /// them to it on the stick (playlist id, dragged synthetic track ids).
    AddUsbTracksToPlaylist(u32, Vec<Id>),
    /// Right-click on a device playlist: copy its tracks into the library and
    /// recreate it as a local playlist (same name, same order).
    ImportUsbPlaylist(u32),
    /// Right-click on a device playlist: save its track list as a text file.
    SaveUsbPlaylistText(u32),
}

/// A pending USB export awaiting the user's confirmation. `playlist_ids`
/// empty = the whole library; otherwise the selected playlist/folder.
/// Counts are computed once when the menu item / button is clicked.
#[derive(Clone)]
struct ExportConfirm {
    dest: PathBuf,
    playlist_ids: Vec<Id>,
    /// What the modal calls the selection ("your entire library",
    /// "playlist “warmup”", …).
    scope: String,
    n_tracks: usize,
    n_playlists: usize,
    /// True = rebuild the stick from this selection alone; false = add to
    /// whatever export is already on it. Scoped playlist exports default to
    /// merge; the whole-library button defaults to replace.
    replace: bool,
}

/// A request raised by a track row's right-click context menu. Collected inside
/// the table closure (which only borrows `self` immutably) and applied after the
/// table, where the `&mut self` operations it needs are available. The `Vec<Id>`
/// targets are the whole selection when the right-clicked row is part of it, else
/// just that row — mirroring how a drag carries its payload.
enum TrackMenuAction {
    /// Start/stop the snippet preview for this track.
    Preview(Id, PathBuf),
    /// Open the convert modal for this track.
    Convert(Id),
    /// Open the batch-convert dialog for these tracks (the multi-selection).
    ConvertSelected(Vec<Id>),
    /// Analyze the target track(s) — BPM, key, beatgrid, transcode check —
    /// skipping any already analyzed at the current analyzer version.
    Analyze(Vec<Id>),
    /// Link the target tracks into a playlist (playlist id, track ids).
    AddToPlaylist(Id, Vec<Id>),
    /// Unlink the target tracks from the viewed playlist; they stay in the catalog.
    RemoveFromPlaylist(Id, Vec<Id>),
    /// Permanently delete the target tracks from the catalog (every playlist + the
    /// analysis cache). Source files are never touched. Gated behind a confirm.
    DeleteFromCatalog(Vec<Id>),
    /// Reorder the target tracks to the front/back of the viewed playlist.
    MoveToTop(Id, Vec<Id>),
    MoveToBottom(Id, Vec<Id>),
    /// Show the source file in Finder.
    RevealInFinder(PathBuf),
    /// Copy the source file's path to the clipboard.
    CopyPath(String),
    /// Copy "Artist – Title" for the target track(s) to the clipboard, one line
    /// per track, formatted as a Soulseek search query.
    CopyForSoulseek(Vec<Id>),
    /// Copy the target device rows' files into the local library and import
    /// them (USB view only).
    AddToLibrary(Vec<Id>),
    /// Open the track's release/album page on Discogs in the browser. Carries
    /// the track id (to look up a previously-fetched release id) and a search
    /// query (artist + album/title) used when no exact release is on file.
    OpenDiscogs(Id, String),
    /// Open the release picker for the target track(s): search Discogs, pick a
    /// release per track, cache its cover and fill the track's empty tag fields.
    /// One action for the whole Discogs match — the old separate "Edit release",
    /// "Fetch artwork" and "Fetch song release details" entries all landed in
    /// this same picker. Works regardless of whether a track was already
    /// fetched, so it doubles as the re-pick.
    FetchRelease(Vec<Id>),
    /// Add the Discogs releases behind the target track(s) to the user's
    /// wantlist. `release_ids` are the deduplicated releases already on file
    /// (several tracks off one record are one want); `fetch_first` are the
    /// selected tracks with no release yet, which get the release picker run
    /// over them before the whole set is wanted. `label` names the release for
    /// the status line.
    AddToWantlist {
        release_ids: Vec<u64>,
        fetch_first: Vec<Id>,
        label: String,
    },
}

fn default_db_path() -> Option<PathBuf> {
    let home = std::env::var_os("HOME")?;
    let dir = PathBuf::from(home).join(".ordnung");
    std::fs::create_dir_all(&dir).ok()?;
    Some(dir.join("catalog.db"))
}
