//! Ordnung GUI — desktop wrapper around `ordnung-core`.
//!
//! Mirrors the CLI's role per `ordnung-architecture`: all policy/UI lives here,
//! engines stay in core. Browses the catalog; double-click a track to convert it.
//! Conversion (and any other I/O) runs in a background thread; the engine itself
//! is the existing `ordnung-core::convert` Phase-4 implementation.

#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod app;
mod audio;
mod config;
mod covers;
mod inspector;
mod jobs;
mod macos_drag;
mod modals;
mod player;
mod sidebar;
mod table;
mod ui;
mod util;
mod views;

use audio::{fmt_time, AudioEngine, PlayState};
use config::Config;
use covers::*;
use eframe::egui;
use egui_extras::{Column, TableBuilder};
use ordnung_core::analysis::{self, AnalysisParams, ANALYZER_VERSION};
use ordnung_core::convert::{self, ConvertSpec};
use ordnung_core::discogs;
use ordnung_core::model::key::Camelot;
use ordnung_core::model::{
    Analysis, Format, Id, Playlist, Tags, Track, TranscodeVerdict, VinylRecord,
};
use ordnung_core::{best_copy_index, scan, tag, Catalog, DuplicateGroup, DuplicateKind};
use player::*;
use rayon::prelude::*;
use sidebar::*;
use std::collections::{HashMap, HashSet, VecDeque};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};
use std::sync::mpsc::{self, Receiver, Sender};
use std::sync::Arc;
use std::thread;
use std::time::Duration;
use table::*;
use ui::hover::HoverNoteExt;
use util::*;

fn main() -> eframe::Result<()> {
    // Pull a repo-root `.env` into the process environment before anything reads
    // it, so a local `DISCOGS_TOKEN=…` line works for `cargo run`/`make run`
    // without exporting it in the shell. Absent file → no-op (Finder launches
    // fall back to the token saved in ~/.ordnung/config.toml); we never override
    // a variable already set in the real environment.
    let _ = dotenvy::dotenv();
    let db_path = default_db_path().unwrap_or_else(|| PathBuf::from("ordnung.db"));
    let mut viewport = egui::ViewportBuilder::default()
        .with_inner_size([1100.0, 680.0])
        .with_min_inner_size([720.0, 420.0])
        .with_title("Ordnung");
    if let Some(icon) = load_app_icon() {
        viewport = viewport.with_icon(icon);
    }
    let opts = eframe::NativeOptions {
        viewport,
        ..Default::default()
    };
    eframe::run_native(
        "Ordnung",
        opts,
        Box::new(move |cc| Ok(Box::new(App::new(db_path, cc.egui_ctx.clone())))),
    )
}

/// Decode the embedded app icon (committed at `assets/icon.png`, generated by
/// `tools/build-app.sh` from `tools/icon.svg`). Returns `None` if the bytes
/// can't be decoded, in which case eframe falls back to its default icon.
fn load_app_icon() -> Option<egui::IconData> {
    let bytes = include_bytes!("../assets/icon.png");
    let img = image::load_from_memory(bytes).ok()?;
    let rgba = img.to_rgba8();
    let (w, h) = rgba.dimensions();
    Some(egui::IconData {
        rgba: rgba.into_raw(),
        width: w,
        height: h,
    })
}

/// One catalog track flattened for display.
struct TrackRow {
    id: Id,
    artist: String,
    title: String,
    album: String,
    genre: String,
    duration: String,
    bpm: String,
    key: String,
    format: Format,
    format_label: String,
    bitrate: String,
    /// Free-text comment from the file's tag (ID3 COMM / Vorbis COMMENT), shown
    /// read-only in the Notes column. Empty string when the track has no comment.
    notes: String,
    /// Pre-formatted relative age for the Added column ("today", "3d ago").
    added: String,
    /// Raw `added_at` unix timestamp (seconds) behind `added`, so the Added
    /// column sorts by true recency rather than the rounded label.
    added_at: i64,
    source_path: PathBuf,
    // Raw values behind the formatted columns, kept so header sorting orders
    // numerically/musically instead of lexically ("100" vs "99", "10A" vs "2A").
    // `None` = unknown ("—" in the cell), and sorts to one end.
    dur_ms: Option<u64>,
    bpm_val: Option<f32>,
    bitrate_val: Option<u32>,
    /// Camelot wheel order: number * 2 + side (B after A within a number).
    key_sort: Option<u16>,
    /// Camelot wheel position behind the `key` label, used to colour the key
    /// chip (harmonic neighbours share a hue). `None` = unanalyzed ("—").
    camelot: Option<Camelot>,
    /// Transcode-quality verdict from spectral analysis. `None` = not analyzed at
    /// v6+ (shows "—"); the Quality column and its sort read from here.
    quality: Option<TranscodeVerdict>,
    /// Detected low-pass cutoff and estimated lossy source, for the cell tooltip.
    quality_cut_hz: Option<f32>,
    quality_src: Option<&'static str>,
    /// Severity rank for sorting (0 clean … 3 likely-lossy); `None` sorts to the end.
    quality_sort: Option<u8>,
    /// Whether this row had embedded cover art at scan time (drives whether we
    /// even try to load a thumbnail from the catalog).
    has_cover: bool,
    /// Whether the catalog has a successfully-fetched external (Discogs)
    /// artwork row for this track. Combined with `has_cover` to decide
    /// whether the cover cell should attempt a load at all.
    has_external_cover: bool,
}

impl TrackRow {
    /// The text the per-column filter matches against for `col` — the same value
    /// the cell shows. Returns `""` for columns without filterable text (Cover),
    /// and the chip label for the Quality column (so e.g. "lossy" matches).
    fn filter_text(&self, col: TableColumn) -> &str {
        match col {
            TableColumn::Cover => "",
            TableColumn::Artist => &self.artist,
            TableColumn::Title => &self.title,
            TableColumn::Album => &self.album,
            TableColumn::Genre => &self.genre,
            TableColumn::Duration => &self.duration,
            TableColumn::Bpm => &self.bpm,
            TableColumn::Key => &self.key,
            TableColumn::Format => &self.format_label,
            TableColumn::Bitrate => &self.bitrate,
            TableColumn::Quality => self.quality.map_or("—", |v| quality_chip(v).0),
            TableColumn::Notes => &self.notes,
            TableColumn::Added => &self.added,
        }
    }
}

/// Cached thumbnail status — `Some(texture)` = ready, `None` = no cover or
/// decode failed (cached so we don't retry every frame).
type CoverEntry = Option<egui::TextureHandle>;

/// Load state of a table-row thumbnail. A *missing* `cover_cache` entry means
/// "not requested yet"; `Loading` means a background decode is in flight (so we
/// don't request it again every frame); `Ready(Some)` is the decoded texture and
/// `Ready(None)` means the track has no usable cover (cached so we never retry).
/// Decoding the PNG and reading the catalog both happen off the UI thread, so a
/// fast scroll never blocks on disk or image decode — the row shows a placeholder
/// until the worker hands back a texture.
enum ThumbState {
    Loading,
    Ready(CoverEntry),
}

/// Which set of tracks the main table shows: the whole catalog ("Library"), the
/// members of one playlist, or the duplicate-finder report. Selected from the
/// left sidebar.
#[derive(Clone, PartialEq, Eq)]
enum LibraryView {
    Library,
    /// The "recently added" inbox — fresh imports that still need analysis and/or
    /// a Discogs song-data fetch. A track expires out of this view automatically
    /// once it's both analyzed (at the current analyzer version) and fetched, so
    /// it reads as a self-clearing to-do list. Backed by the flat track table.
    RecentlyAdded,
    Playlist(Id),
    /// The duplicate finder — rendered as grouped blocks, not the flat table.
    Duplicates,
    /// Tracks whose source file is gone — rendered as a review list, not the table.
    Missing,
    /// The user's Discogs vinyl collection — rendered as a grid of cover art,
    /// not the flat track table. Backed by the local `vinyl_collection` cache.
    Vinyl,
}

/// A sortable table column. The cover column isn't sortable, so it has no
/// variant. Paired with a direction (`true` = ascending) in `App::sort`.
#[derive(Clone, Copy, PartialEq, Eq)]
enum SortColumn {
    Artist,
    Title,
    Album,
    Genre,
    Duration,
    Bpm,
    Key,
    Format,
    Bitrate,
    Quality,
    Notes,
    Added,
}

/// One column of the track table. The cover thumbnail plus the ten data columns
/// are reorderable and show/hideable from the header's right-click menu; the
/// chosen order and hidden set persist to `~/.ordnung/config.toml`. The trailing
/// `remainder` spacer is structural (it just fills slack so the striped rows span
/// the full width) and is intentionally not represented here.
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
enum TableColumn {
    Cover,
    Artist,
    Title,
    Album,
    Genre,
    Duration,
    // Temporarily not shown (omitted from `DEFAULT_ORDER`) while tempo detection
    // is reworked, so it's never constructed right now — keep the variant and its
    // match arms intact for a one-line restore.
    #[allow(dead_code)]
    Bpm,
    Key,
    Format,
    Bitrate,
    Quality,
    /// Free-text notes — the file's comment tag (ID3 COMM / Vorbis COMMENT),
    /// surfaced read-only here. See `Tags::comment` in ordnung-core.
    Notes,
    /// When the track was first scanned into the catalog (`tracks.added_at`),
    /// shown as a relative age ("today", "3d ago"). Sort it descending to see
    /// the most recent import at the top.
    Added,
}

impl TableColumn {
    /// Every column in the default left-to-right order. Doubles as the source of
    /// truth for "which columns exist": the reorder menu lists these, and loading
    /// a saved layout appends any column missing from it (so a config written by
    /// an older build still shows columns added since).
    // NOTE: `Bpm` is intentionally omitted here — the BPM column is hidden for now
    // while tempo detection is being reworked (stored BPM values were cleared too).
    // The `TableColumn::Bpm` variant and all its match arms are kept so re-adding
    // this one line restores the column. Because `from_key`/`load_column_layout`
    // only resolve columns present in this list, a saved layout containing "bpm"
    // also drops it cleanly.
    const DEFAULT_ORDER: [TableColumn; 12] = [
        TableColumn::Cover,
        TableColumn::Artist,
        TableColumn::Title,
        TableColumn::Album,
        TableColumn::Genre,
        TableColumn::Duration,
        TableColumn::Added,
        TableColumn::Key,
        TableColumn::Format,
        TableColumn::Bitrate,
        TableColumn::Quality,
        TableColumn::Notes,
    ];

    /// Stable key persisted to config — deliberately independent of the enum
    /// order and the display label so reordering the enum or renaming a header
    /// can't corrupt a saved layout.
    fn key(self) -> &'static str {
        match self {
            TableColumn::Cover => "cover",
            TableColumn::Artist => "artist",
            TableColumn::Title => "title",
            TableColumn::Album => "album",
            TableColumn::Genre => "genre",
            TableColumn::Duration => "duration",
            TableColumn::Bpm => "bpm",
            TableColumn::Key => "key",
            TableColumn::Format => "format",
            TableColumn::Bitrate => "bitrate",
            TableColumn::Quality => "quality",
            TableColumn::Notes => "notes",
            TableColumn::Added => "added",
        }
    }

    /// Parse a persisted key back into a column, ignoring anything unknown (a key
    /// from a newer build, or a typo'd hand-edited config).
    fn from_key(s: &str) -> Option<TableColumn> {
        TableColumn::DEFAULT_ORDER
            .into_iter()
            .find(|c| c.key() == s)
    }

    /// Display name: the header text, and the row label in the reorder menu. The
    /// cover header draws no text, but the column still needs a name in the menu.
    fn label(self) -> &'static str {
        match self {
            TableColumn::Cover => "Cover",
            TableColumn::Artist => "Artist",
            TableColumn::Title => "Title",
            TableColumn::Album => "Album",
            TableColumn::Genre => "Genre",
            TableColumn::Duration => "Dur",
            TableColumn::Bpm => "BPM",
            TableColumn::Key => "Key",
            TableColumn::Format => "Format",
            TableColumn::Bitrate => "kbps",
            TableColumn::Quality => "Qual",
            TableColumn::Notes => "Notes",
            TableColumn::Added => "Added",
        }
    }

    /// The sort key cycled by clicking this header, or `None` for the (unsortable)
    /// cover column.
    fn sort_column(self) -> Option<SortColumn> {
        Some(match self {
            TableColumn::Cover => return None,
            TableColumn::Artist => SortColumn::Artist,
            TableColumn::Title => SortColumn::Title,
            TableColumn::Album => SortColumn::Album,
            TableColumn::Genre => SortColumn::Genre,
            TableColumn::Duration => SortColumn::Duration,
            TableColumn::Bpm => SortColumn::Bpm,
            TableColumn::Key => SortColumn::Key,
            TableColumn::Format => SortColumn::Format,
            TableColumn::Bitrate => SortColumn::Bitrate,
            TableColumn::Quality => SortColumn::Quality,
            TableColumn::Notes => SortColumn::Notes,
            TableColumn::Added => SortColumn::Added,
        })
    }

    /// This column's egui_extras width spec (the same sizes the table used when
    /// columns were hard-coded). `cover_px` is the thumbnail edge length.
    /// `width` overrides the initial width with the user's saved value (see
    /// `App::column_widths`); `None` uses the per-column default. The Cover column
    /// is a fixed size and ignores the override.
    fn spec(self, cover_px: f32, width: Option<f32>) -> Column {
        let w = |default: f32| width.unwrap_or(default);
        match self {
            TableColumn::Cover => Column::exact(cover_px + 6.0),
            TableColumn::Artist => Column::initial(w(180.0)).at_least(80.0).clip(true),
            TableColumn::Title => Column::initial(w(260.0)).at_least(80.0).clip(true),
            TableColumn::Album => Column::initial(w(180.0)).at_least(60.0).clip(true),
            TableColumn::Genre => Column::initial(w(110.0)).at_least(60.0).clip(true),
            TableColumn::Duration => Column::initial(w(60.0)).at_least(40.0),
            TableColumn::Bpm => Column::initial(w(55.0)).at_least(40.0),
            TableColumn::Key => Column::initial(w(55.0)).at_least(40.0),
            TableColumn::Format => Column::initial(w(60.0)).at_least(50.0),
            TableColumn::Bitrate => Column::initial(w(70.0)).at_least(50.0),
            TableColumn::Quality => Column::initial(w(66.0)).at_least(48.0),
            TableColumn::Notes => Column::initial(w(200.0)).at_least(80.0).clip(true),
            TableColumn::Added => Column::initial(w(90.0)).at_least(60.0),
        }
    }
}

/// Open state for the per-column filter search bar (double-click a header). The
/// bar anchors at `pos`; `focus` is true for the one frame after opening so the
/// text field grabs the keyboard without an extra click.
struct ColFilterPopup {
    col: TableColumn,
    pos: egui::Pos2,
    focus: bool,
}

/// egui drag-and-drop payload carried by a plain row-drag: the track ids being
/// dragged (the whole selection, in visible order). Dropping it onto a playlist
/// in the left sidebar adds those tracks. (Option-drag uses the native macOS
/// drag-out to rekordbox instead and never sets this payload.)
#[derive(Clone)]
struct DraggedTracks(Vec<Id>);

/// Edit buffers for the inspector's editable Core tag fields. Held as plain
/// strings so they bind directly to `TextEdit`s; converted back to typed `Tags`
/// on save. Compared against a saved baseline to drive the dirty state.
#[derive(Default, Clone, PartialEq, Eq)]
struct TagEdit {
    title: String,
    artist: String,
    album_artist: String,
    album: String,
    genre: String,
    label: String,
    year: String,
    comment: String,
}

impl TagEdit {
    fn from_tags(t: &Tags) -> Self {
        TagEdit {
            title: t.title.clone().unwrap_or_default(),
            artist: t.artist.clone().unwrap_or_default(),
            album_artist: t.album_artist.clone().unwrap_or_default(),
            album: t.album.clone().unwrap_or_default(),
            genre: t.genre.clone().unwrap_or_default(),
            label: t.label.clone().unwrap_or_default(),
            year: t.year.map(|y| y.to_string()).unwrap_or_default(),
            comment: t.comment.clone().unwrap_or_default(),
        }
    }
}

/// What the user asked the inspector to do this frame. Returned from
/// `draw_inspector` and acted on after its borrow of `self` ends.
enum InspectorAction {
    /// Imprint the fetched external cover into the source file.
    EmbedCover(Id, PathBuf),
    /// Commit the edited Core fields to the catalog only.
    SaveToCatalog(Id),
    /// Commit to the catalog AND write the tags into the source file.
    WriteToFile(Id, PathBuf),
}

/// State for the conversion modal. Also lets the user rename the track
/// (catalog-only — never touches the source file unless they convert in-place,
/// and even then only the bytes are rewritten, not the tags).
struct ConvertModal {
    track_id: Id,
    track_label: String,
    source_path: PathBuf,
    source_format: Format,
    // Editable display name. Saved to catalog tags via `update_tags`.
    edit_title: String,
    edit_artist: String,
    edit_album: String,
    name_status: Option<String>,
    name_is_error: bool,
    // Conversion options.
    target: Format,
    bitrate_kbps: String,
    out_dir: Option<PathBuf>,
    in_place: bool,
    error: Option<String>,
}

/// Batch conversion of the current multi-selection to one target format. Unlike
/// `ConvertModal` there's no per-track name editing — just the shared conversion
/// options applied to every selected track. Each output is rehydrated from the
/// catalog (full tags + cover), exactly like a single convert.
struct BatchConvert {
    ids: Vec<Id>,
    target: Format,
    bitrate_kbps: String,
    out_dir: Option<PathBuf>,
    in_place: bool,
    error: Option<String>,
}

/// One Discogs release option for a track: metadata + image URLs + a small
/// preview thumbnail. The full-resolution image is downloaded lazily when the
/// user picks this candidate (see `save_selected_artwork`).
struct ArtworkChoice {
    release_id: String,
    title: String,
    year: String,
    label: String,
    country: String,
    format: String,
    thumb_url: String,
    cover_image_url: String,
    thumb_png: Vec<u8>,
}

/// All candidate releases fetched for one track, awaiting the user's pick.
struct ArtworkChoices {
    id: Id,
    label: String,
    candidates: Vec<ArtworkChoice>,
}

/// An image file dropped onto a track row, awaiting the user's confirmation to
/// set it as that track's cover. Drives the cover-drop modal (a popup that asks
/// before writing anything). The image is decoded and re-encoded to PNG up front
/// so both the modal preview and the stored cover use validated bytes.
struct CoverDrop {
    /// The track the image was dropped on (the primary target).
    track_id: Id,
    /// "Artist — Title" of the target track, for the modal header.
    track_label: String,
    /// Album name of the target track, shown when offering to apply to mates.
    album: String,
    /// Source path of the dropped image (shown small in the modal).
    image_path: PathBuf,
    /// Re-encoded PNG of the full image — stored as the cover and embeddable.
    full_png: Vec<u8>,
    /// Re-encoded, downscaled PNG used as the table thumbnail.
    thumb_png: Vec<u8>,
    /// Decoded preview texture for the modal (built lazily on first draw).
    preview: Option<egui::TextureHandle>,
    /// Other tracks on the same album, each with a checkbox to also receive the
    /// cover. Cover-less mates are pre-checked; mates that already have art start
    /// unchecked so an existing cover isn't clobbered without an explicit tick.
    siblings: Vec<CoverSibling>,
}

/// One album-mate row in the cover-drop modal's "apply to these too" selector.
struct CoverSibling {
    id: Id,
    label: String,
    has_art: bool,
    selected: bool,
}

/// Result of a finished background artwork save: the picked track (`id`) and the
/// album-mates the same cover was copied onto (`also`, empty when not propagated).
/// The UI uses `also` to drop the stale cached thumbnails of overwritten siblings.
struct ArtSaveDone {
    id: Id,
    also: Vec<Id>,
}

/// Messages the worker thread can send back to the UI.
enum JobMsg {
    Status(String),
    /// Determinate progress for the running job: `done` of `total` items
    /// finished. Drives the status-bar progress bar.
    Progress {
        done: usize,
        total: usize,
    },
    Done(String),
    Failed(String),
    /// Per-item failures from a background job: `(item name, reason)`, with a
    /// `title` naming what was attempted (e.g. "Scan", "Write edits"). Sent just
    /// before `Done` whenever a job skipped or errored on any item, so the UI
    /// can show the user exactly what didn't go through and why.
    Failures {
        title: String,
        items: Vec<(String, String)>,
    },
    /// Candidate releases fetched for one track, for the user to pick from.
    ArtworkChoices(ArtworkChoices),
    /// The Discogs username resolved during a vinyl sync, so the UI can persist
    /// it (config) and link to the user's collection page.
    VinylUsername(String),
}

/// Result of a background full-resolution cover load. The decode (potentially a
/// multi-megapixel JPEG) happens off the UI thread; the main thread turns the
/// pixels into a texture. `image` is `None` when the track has no usable cover.
struct CoverLoaded {
    id: Id,
    image: Option<egui::ColorImage>,
}

/// Result of a background "what would this release fill in?" lookup, computed for
/// the "Fetch song data" picker so the user can see the data before committing.
/// Carries the human-readable (field, value) rows to display and the underlying
/// `ReleaseDetail` to reuse on apply (so we don't fetch the release twice).
struct PreviewMsg {
    track_id: Id,
    release_id: String,
    /// Whether this preview was computed in overwrite mode — part of the cache
    /// key, so it must round-trip back from the worker.
    overwrite: bool,
    /// `(field label, value)` for each field this release would write under the
    /// current mode. Empty when the release adds nothing new or the lookup failed.
    fills: Vec<(String, String)>,
    /// `None` when the release lookup failed (network/decode).
    detail: Option<discogs::ReleaseDetail>,
}

struct App {
    db_path: PathBuf,
    rows: Vec<TrackRow>,
    filter: String,
    /// The primary/active row — drives the inspector. Always the last row the
    /// user clicked (and a member of `selection` whenever `selection` is non-empty).
    selected: Option<Id>,
    /// Every selected row. Single click selects one; Cmd-click toggles; Shift-click
    /// extends a contiguous range. Drives the row highlight and which tracks a
    /// drag-out carries. Kept in sync with the visible `rows` on reload.
    selection: HashSet<Id>,
    /// Anchor row for Shift-click range selection (the last non-shift click).
    select_anchor: Option<Id>,
    /// Full Track (every tag) for the inspector panel — fetched on selection.
    selected_track: Option<Track>,
    /// Whether the selected track has full-resolution fetched artwork on record
    /// (drives the inspector's "embed cover into file" action). Refreshed with
    /// `selected_track`.
    selected_has_external_art: bool,
    convert_modal: Option<ConvertModal>,
    /// Open batch-convert dialog for the current selection, or `None`.
    batch_convert: Option<BatchConvert>,
    job_rx: Option<Receiver<JobMsg>>,
    status: String,
    /// Last status string we saw and the egui time (seconds) it appeared, used
    /// to fade an idle status message out of the bottom-left bar after a few
    /// seconds. Only idle messages expire; while a job runs the status stays.
    status_last: String,
    status_shown_at: f64,
    /// Determinate progress of the running job (`done`, `total`), or `None` when
    /// idle or running a job that doesn't report item counts. Drives the
    /// status-bar progress bar; cleared when the job finishes.
    progress: Option<(usize, usize)>,
    load_error: Option<String>,
    /// Decoded thumbnail textures keyed by track id. Lazy-populated for visible
    /// rows; see `ThumbState` for what each entry means. Reads (catalog + PNG
    /// decode) run on the `thumb` worker thread so scrolling never stalls.
    cover_cache: HashMap<Id, ThumbState>,
    /// Sends a track id to the persistent thumbnail worker, asking it to load and
    /// decode that row's small cover off the UI thread.
    thumb_req_tx: Sender<Id>,
    /// Receives finished thumbnail decodes from the worker; drained each frame by
    /// `poll_thumbs`, which uploads the texture (a UI-thread-only op) and caches it.
    thumb_rx: Receiver<CoverLoaded>,
    /// Decoded *full-resolution* cover textures for the inspector preview, keyed
    /// by track id. Separate from `cover_cache` (the small table thumbnails) so
    /// the table stays cheap while the inspector shows high-quality art. Filled
    /// asynchronously: a `None` entry means "loaded, no cover"; a missing entry
    /// means "not loaded" (possibly in flight — see `cover_inflight`).
    cover_full_cache: HashMap<Id, CoverEntry>,
    /// Track ids whose full cover is currently decoding on a background thread.
    /// Prevents spawning duplicate loaders and drives the "loading…" placeholder.
    cover_inflight: HashSet<Id>,
    /// Persistent channel for finished cover decodes. Loader threads clone the
    /// sender; the UI drains the receiver each frame and builds textures.
    cover_tx: Sender<CoverLoaded>,
    cover_rx: Receiver<CoverLoaded>,
    /// The user's cached Discogs vinyl collection, shown in the `Vinyl` grid view.
    /// Repopulated from the `vinyl_collection` table on every `reload`.
    vinyl: Vec<VinylRecord>,
    /// Count of cached vinyl records, for the sidebar label. Kept fresh on reload
    /// so the badge is right even when the grid isn't the active view.
    vinyl_count: u64,
    /// Decoded vinyl cover textures keyed by Discogs `instance_id` (reuses
    /// `ThumbState`). Loaded lazily by the vinyl-cover worker as cells render,
    /// mirroring `cover_cache` for table rows.
    vinyl_covers: HashMap<u64, ThumbState>,
    /// Asks the vinyl-cover worker to load + decode one record's cached cover.
    vinyl_cover_req_tx: Sender<u64>,
    /// Finished vinyl-cover decodes (reuses `CoverLoaded`; `id` carries the
    /// `instance_id`). Drained each frame, uploaded to a texture, and cached.
    vinyl_cover_rx: Receiver<CoverLoaded>,
    /// Discogs `release_id` → catalog track ids that link to it (via fetched
    /// artwork/metadata). Lets the vinyl grid flag records you already own a
    /// digital copy of and jump to them. Rebuilt with `vinyl` on reload.
    vinyl_links: HashMap<u64, Vec<Id>>,
    /// A track the table should scroll to and reveal on the next frame, set when
    /// jumping into the catalog from the vinyl grid. Cleared once honoured.
    scroll_to_track: Option<Id>,
    /// Screen-space rect of each visible table row this frame, with its track id.
    /// Filled in `draw_table` and read by `handle_file_drop` to map a dropped
    /// image onto the row under the cursor. Rebuilt every frame.
    row_screen_rects: Vec<(Id, egui::Rect)>,
    /// An image dropped onto a track row, awaiting confirmation to set it as that
    /// track's cover. `Some` shows the cover-drop modal. See [`CoverDrop`].
    cover_drop: Option<CoverDrop>,
    show_inspector: bool,
    /// Set while a cancellable job (scan / artwork fetch) is running; the worker
    /// polls it and stops early. `None` when idle or running a non-cancellable job.
    job_cancel: Option<Arc<AtomicBool>>,
    /// Per-track candidate releases waiting for the user to pick (front first).
    artwork_queue: VecDeque<ArtworkChoices>,
    /// Whether picking a candidate should also fill in the track's missing
    /// album-level tag fields from the chosen release ("Fetch song data" button),
    /// or just cache the cover ("Fetch artwork" button — harmless, no tag edits).
    /// Set when the fetch run is launched; read when a candidate is saved.
    artwork_enrich: bool,
    /// In a song-data run, whether committing a release *replaces* existing tag
    /// values (true) or only fills empty ones (false, the default). Toggled by a
    /// checkbox in the picker; read when a candidate is saved and woven into the
    /// field preview so what's shown matches what gets written.
    artwork_overwrite: bool,
    /// In a song-data run, whether committing the chosen release also sets the
    /// track's cover from it. Defaulted per front track when the picker advances:
    /// off when the track already has art (so enriching tags never clobbers an
    /// existing cover), on when it has none. Toggled by a checkbox in the picker;
    /// read when a candidate is saved. The "Fetch artwork" run ignores this — there
    /// the cover *is* the point and is always written.
    artwork_set_cover: bool,
    /// Whether saving the chosen cover should also copy it to the front track's
    /// album-mates. One lookup then dresses a whole album. Toggled by a checkbox in
    /// the picker that only appears when album-mates exist; read when a candidate
    /// is saved.
    artwork_apply_album: bool,
    /// Within an "apply to album" save, whether to also *overwrite* album-mates
    /// that already have their own cover (true → every album-mate matches), or
    /// only fill the cover-less ones (false, the safe default).
    artwork_album_overwrite: bool,
    /// Cached album-mate counts for the front track — `(id, missing, total)` where
    /// `missing` is cover-less mates and `total` is all mates. Keyed by id so the
    /// DB is queried once per track, not every frame. Drives the checkbox labels
    /// and which controls appear.
    artwork_album_count: Option<(Id, usize, usize)>,
    /// Cached album-mate details for the front track of the artwork picker —
    /// `(id, [(id, label, has_art)])`. Computed once per front track (alongside
    /// `artwork_album_count`) so the picker can list *which* songs share the
    /// chosen cover by name, not just a count.
    artwork_album_siblings: Option<(Id, Vec<(Id, String, bool)>)>,
    /// Index of the currently highlighted candidate for the front track.
    artwork_selected: usize,
    /// Decoded preview thumbnails for the front track's candidates, keyed by
    /// track id so we only re-decode when the front track changes.
    artwork_previews: Option<(Id, Vec<Option<egui::TextureHandle>>)>,
    /// True while the chosen cover's full-resolution image is downloading and
    /// being written on a background thread. Drives the Save button's spinner
    /// and blocks the picker's controls so the front track can't change until
    /// the save lands.
    artwork_saving: bool,
    /// Channel carrying a finished background artwork save (the picked track plus
    /// any album-mates the cover was propagated to). The saver thread clones the
    /// sender; the UI drains the receiver each frame to advance the queue and
    /// refresh caches once the save has actually landed.
    art_save_tx: Sender<ArtSaveDone>,
    art_save_rx: Receiver<ArtSaveDone>,
    /// Channel for finished "Fetch song data" field previews (which fields a
    /// candidate release would fill). Worker threads clone the sender; the UI
    /// drains the receiver each frame into `preview_cache`.
    preview_tx: Sender<PreviewMsg>,
    preview_rx: Receiver<PreviewMsg>,
    /// Computed field previews keyed by `(track id, release id, overwrite)`: the
    /// `(label, value)` rows shown in the song-data picker. The `overwrite` flag
    /// is part of the key because it changes which fields a release would write.
    /// An entry means the lookup finished (possibly with zero rows); absence
    /// means "not loaded".
    preview_cache: HashMap<(Id, String, bool), Vec<(String, String)>>,
    /// `(track id, release id, overwrite)` previews currently being fetched, so
    /// we don't spawn duplicate lookups and can show a spinner while one runs.
    preview_inflight: HashSet<(Id, String, bool)>,
    /// Fetched `ReleaseDetail`s keyed by release id, kept so applying a chosen
    /// release reuses the preview's fetch instead of hitting Discogs again.
    release_detail_cache: HashMap<String, discogs::ReleaseDetail>,
    /// Persistent settings (Discogs token), loaded from `~/.ordnung/config.toml`.
    config: Config,
    /// Visible-and-hidden track-table columns in left-to-right order, reordered
    /// via the header right-click menu and persisted to config. Always a
    /// permutation of `TableColumn::DEFAULT_ORDER`; entries in `hidden_columns`
    /// keep their slot here (so re-showing restores their position) but aren't
    /// drawn.
    column_order: Vec<TableColumn>,
    /// Columns hidden via the reorder menu — not drawn, but still listed in the
    /// menu so they can be brought back.
    hidden_columns: HashSet<TableColumn>,
    /// User-resized track-table column widths (points), keyed by column. Shared
    /// across every view and persisted to config so a resize in one playlist
    /// applies everywhere and survives rebuilds. Absent columns use their default
    /// width. Mirrors `config.column_widths`; the table reads it to seed each
    /// column and writes observed widths back after a resize.
    column_widths: HashMap<TableColumn, f32>,
    /// Set when `column_widths` changed this frame from a live resize; the new
    /// widths are flushed to config once the drag ends (pointer released) so a
    /// drag doesn't rewrite the TOML on every frame.
    column_widths_dirty: bool,
    /// Set by "Reset to default" in the column menu; consumed by the next table
    /// build to also clear egui_extras' own stored widths (which otherwise
    /// override the freshly-cleared defaults until a rebuild).
    reset_column_widths: bool,
    /// When `Some`, the column reorder popup is open, anchored at this screen
    /// position (where the header was right-clicked).
    column_menu: Option<egui::Pos2>,
    /// Per-column "filter by this column's values" text, keyed by column. Set
    /// from the popup opened by double-clicking a header; an absent or empty
    /// entry means that column isn't filtering. Applied in-memory over the
    /// loaded rows (on top of the global `filter`), so it composes with the
    /// global search and the active sort.
    col_filters: HashMap<TableColumn, String>,
    /// When `Some`, the per-column filter search bar is open (a header was
    /// double-clicked); mirrors `column_menu`.
    col_filter_open: Option<ColFilterPopup>,
    /// Whether the Settings window is open.
    settings_open: bool,
    /// Edit buffer for the token field while the Settings window is open.
    token_input: String,
    /// Whether the "clear the whole catalog?" confirmation popup is showing.
    confirm_clear_db: bool,
    /// Title of the failure report (which job produced it).
    failure_report_title: String,
    /// Per-item failures `(item name, reason)` from the last job that had any.
    /// Drives the failure-report popup; empty when nothing failed.
    failure_report: Vec<(String, String)>,
    /// Whether the failure-report popup is open.
    show_failure_report: bool,
    /// Audio output for the cover snippet-preview button. `None` if the machine
    /// has no usable output device (the button is then hidden).
    audio: Option<AudioEngine>,
    /// Carries the now-playing track's resolved cover (a `file://` temp-file URL,
    /// or `None`) back from the off-thread loader so the OS Now Playing panel can
    /// show artwork. Tagged with the track `Id` to ignore stale results.
    media_cover_tx: Sender<(Id, Option<String>)>,
    media_cover_rx: Receiver<(Id, Option<String>)>,
    /// Live edit buffers for the inspector's editable Core fields (current
    /// selection). Repopulated whenever the selection changes or a save lands.
    tag_edit: TagEdit,
    /// Snapshot of `tag_edit` as last loaded/saved; `tag_edit != tag_edit_saved`
    /// means there are unsaved edits (drives the Save / Write button state).
    tag_edit_saved: TagEdit,
    /// Cached count of tracks with catalog edits not yet written to their source
    /// files (`user_edited`). Refreshed on every `reload`; drives the toolbar's
    /// bulk "write edits to files" button label and enabled state.
    edited_count: u64,
    /// Cached count of tracks whose source file is missing from disk. Refreshed
    /// after jobs and on Refresh (not on every filter keystroke — file existence
    /// doesn't change with the filter). Drives the toolbar's "relocate missing"
    /// button, which only appears when this is non-zero.
    missing_count: u64,
    /// How many tracks sit in the "recently added" inbox — fresh imports not yet
    /// both analyzed and song-data fetched. Refreshed on every `reload` (it's a
    /// cheap count) so the sidebar's Recent badge stays live as tracks expire out
    /// of the view. See [`LibraryView::RecentlyAdded`].
    recent_count: u64,
    /// Track ids currently pinned into the [`LibraryView::RecentlyAdded`] table:
    /// the rows shown the last time it was loaded while the tab was open. A track
    /// that finishes (analyzed + fetched) while you're looking at Recent stays
    /// here so it doesn't vanish mid-glance; the set is cleared when you leave the
    /// tab, so re-entering recomputes the live inbox and the finished track drops
    /// off. Empty whenever the Recent tab isn't the active view.
    recent_pinned: HashSet<Id>,
    /// "Artist — Title" labels for the missing tracks, refreshed alongside
    /// `missing_count`. Drives the relocate button's hover list so it works from
    /// any view (unlike `missing_list`, which only fills in the Missing view).
    missing_labels: Vec<String>,
    /// Whether the "write N edited tracks to their files?" confirmation is open.
    confirm_bulk_write: bool,
    /// Track ids pending a "delete from catalog?" confirmation, if that dialog is
    /// open. `Some` shows the modal; confirming deletes them from the catalog.
    confirm_delete: Option<Vec<Id>>,
    /// True while a bulk write-edits job is the active worker. Lets the job's
    /// completion handler drop cover textures, since that job may have embedded
    /// fetched art and the per-id texture cache would otherwise show stale covers.
    write_edits_running: bool,
    /// Playlists & folders, refreshed on every `reload`. Drives the left sidebar.
    playlists: Vec<Playlist>,
    /// Duplicate groups for the Duplicates view. Computed off the UI thread (the
    /// acoustic-fingerprint scan is a full-catalog pass and would otherwise freeze
    /// the frame on click) and cached here between scans. Drives `draw_duplicates`.
    dup_groups: Vec<DuplicateGroup>,
    /// Set when the cached `dup_groups` may be stale and a rescan is wanted — on
    /// entering the view, an explicit Recompute, or a catalog mutation. A pending
    /// scan is kicked off from `update` (which has the egui `Context` the worker
    /// needs to wake the UI); coalesced so reload bursts spawn at most one rescan.
    dup_dirty: bool,
    /// A background duplicate scan is in flight. Gates re-spawning and drives the
    /// view's "Scanning…" spinner. The result arrives over `dup_rx`.
    dup_loading: bool,
    /// Receives the finished duplicate groups from the background scan worker.
    dup_rx: Option<std::sync::mpsc::Receiver<Vec<DuplicateGroup>>>,
    /// Per-copy keep/delete decisions in the Duplicates view, keyed by track id —
    /// `true` means "marked for deletion". Each group is seeded the first time it
    /// appears (best copy kept, the rest marked) and the user revises the marks
    /// before committing; entries for copies no longer in any group are pruned on
    /// every render. The "Delete N marked" button commits every `true` entry in
    /// one background pass. Reviewing is pure state — no disk IO — so marking
    /// never blocks.
    dup_decisions: HashMap<Id, bool>,
    /// A staged "delete the marked copies" batch awaiting confirmation. Holds the
    /// marked copies `(keeper id, drop id, source path)` to trash — the keeper is
    /// the kept copy in each group, which inherits the dropped copy's playlist
    /// slots. Confirming hands the batch to a background job. `None` when no batch
    /// is pending.
    dup_pending_bulk: Option<Vec<(Id, Id, PathBuf)>>,
    /// Screen position of the click that staged the pending duplicate
    /// delete/bulk, so the confirmation modal opens right under the cursor
    /// instead of dead-center (no mouse swipe to reach the confirm button).
    /// `None` falls back to a centered modal.
    dup_confirm_pos: Option<egui::Pos2>,
    /// Tracks whose source file is gone, for the Missing files view. Recomputed on
    /// `reload` while that view is active (empty otherwise). Drives `draw_missing`.
    missing_list: Vec<Track>,
    /// Missing tracks the user clicked "Remove" on, awaiting confirmation. Holds the
    /// row ids to drop from the catalog (their files are already gone — removal never
    /// touches a real file). `None` when no confirmation is pending.
    missing_pending_remove: Option<Vec<Id>>,
    /// Which track set the table shows — the whole library or one playlist.
    view: LibraryView,
    /// Inline rename in progress for a sidebar entry, or `None` when no row is
    /// being edited.
    renaming: Option<Renaming>,
    /// Active table sort: which column and direction (`true` = ascending).
    /// `None` keeps the natural order (catalog order, or the playlist's manual
    /// order). Set by clicking a column header.
    sort: Option<(SortColumn, bool)>,
    /// Display info for the track in the bottom now-playing bar — title/artist and
    /// the source path (used to lazily load its cover). Set when playback starts;
    /// the bar is shown while the engine still has this track loaded or decoding.
    now_playing: Option<NowPlaying>,
    /// Fraction `[0, 1]` the user is dragging the scrubber to, before release. The
    /// actual seek fires on release so we rebuild the audio sink once, not per
    /// frame; `None` when not scrubbing.
    scrub: Option<f32>,
}

/// What the bottom player bar needs to render the current track.
struct NowPlaying {
    id: Id,
    artist: String,
    title: String,
    source_path: String,
}

/// State for the inline text box that names a sidebar playlist.
struct Renaming {
    /// The playlist (or folder) being edited.
    id: Id,
    /// Live edit buffer bound to the `TextEdit`.
    buf: String,
    /// True when the row was just created, so an empty/cancelled edit removes it
    /// instead of leaving a blank placeholder behind.
    is_new: bool,
    /// Set on the frame the editor appears so we grab focus exactly once. If we
    /// re-requested focus every frame the box could never lose focus, so
    /// clicking away to commit/cancel would be impossible.
    needs_focus: bool,
}

/// A catalog-mutating request raised by the left sidebar, applied after the
/// panel closure ends so it doesn't borrow `self` while the tree is rendering.
enum SidebarAction {
    /// Create a playlist under the given parent folder (`None` = top level).
    NewPlaylist(Option<Id>),
    Rename(Id, String),
    Delete(Id),
    /// Tracks dropped onto a playlist (playlist id, dragged track ids).
    AddTracks(Id, Vec<Id>),
}

/// A request raised by a track row's right-click context menu. Collected inside
/// the table closure (which only borrows `self` immutably) and applied after the
/// table, where the `&mut self` operations it needs are available. The `Vec<Id>`
/// targets are the whole selection when the right-clicked row is part of it, else
/// just that row — mirroring how a drag carries its payload.
enum TrackMenuAction {
    /// Start/stop the snippet preview for this track.
    Preview(Id, PathBuf),
    /// Open the convert modal for this track.
    Convert(Id),
    /// Open the batch-convert dialog for these tracks (the multi-selection).
    ConvertSelected(Vec<Id>),
    /// Analyze the target track(s) — BPM, key, beatgrid, transcode check —
    /// skipping any already analyzed at the current analyzer version.
    Analyze(Vec<Id>),
    /// Link the target tracks into a playlist (playlist id, track ids).
    AddToPlaylist(Id, Vec<Id>),
    /// Unlink the target tracks from the viewed playlist; they stay in the catalog.
    RemoveFromPlaylist(Id, Vec<Id>),
    /// Permanently delete the target tracks from the catalog (every playlist + the
    /// analysis cache). Source files are never touched. Gated behind a confirm.
    DeleteFromCatalog(Vec<Id>),
    /// Reorder the target tracks to the front/back of the viewed playlist.
    MoveToTop(Id, Vec<Id>),
    MoveToBottom(Id, Vec<Id>),
    /// Show the source file in Finder.
    RevealInFinder(PathBuf),
    /// Copy the source file's path to the clipboard.
    CopyPath(String),
    /// Copy "Artist – Title" for the target track(s) to the clipboard, one line
    /// per track, formatted as a Soulseek search query.
    CopyForSoulseek(Vec<Id>),
    /// Open the track's release/album page on Discogs in the browser. Carries
    /// the track id (to look up a previously-fetched release id) and a search
    /// query (artist + album/title) used when no exact release is on file.
    OpenDiscogs(Id, String),
    /// Re-open the release picker for a single track to (re)choose its Discogs
    /// release — applying that release's cover and filling empty tag fields.
    /// Works regardless of whether the track was already fetched.
    EditRelease(Id),
    /// Fetch cover art only for the target track(s): search Discogs, pick a
    /// release per track, cache its cover. Never touches tags.
    FetchArtwork(Vec<Id>),
    /// Fetch full song details for the target track(s): search Discogs, pick a
    /// release per track, cache its cover and fill the track's empty tag fields.
    FetchSongDetails(Vec<Id>),
}

fn default_db_path() -> Option<PathBuf> {
    let home = std::env::var_os("HOME")?;
    let dir = PathBuf::from(home).join(".ordnung");
    std::fs::create_dir_all(&dir).ok()?;
    Some(dir.join("catalog.db"))
}
